import assert from 'node:assert/strict'
import {test} from 'node:test'
import {build} from 'esbuild'
import {readFileSync,readdirSync} from 'node:fs'
const css=readdirSync('.next/static/chunks').filter(file=>file.endsWith('.css')).sort().map(file=>readFileSync('.next/static/chunks/'+file,'utf8')).join('\n')
import {chromium,type Browser,type Page} from 'playwright-core'
const bundle=build({stdin:{loader:'tsx',resolveDir:process.cwd(),contents:`import React from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{RecoveryDialog}from'./src/components/desktop/RecoveryDialog';import{desktopRecoveryStore,installRecoveryDraftSource}from'./src/lib/desktop/draft-recovery';import{desktopSaveCoordinator}from'./src/lib/desktop/save-coordinator';import{useDesktopStore}from'./src/stores/desktop';globalThis.mount=items=>{const copied=[],exports=[];desktopRecoveryStore.retain(items);installRecoveryDraftSource(desktopSaveCoordinator);useDesktopStore.setState({bootstrap:{draftSessionId:crypto.randomUUID()}});window.desktop={workBackup:async()=>({type:'works',works:[]}),writeClipboardText:async text=>{copied.push(text)},exportDraft:async(id,value)=>{exports.push(value);return true}};const root=createRoot(document.getElementById('app'));flushSync(()=>root.render(React.createElement(RecoveryDialog,{open:true,onOpenChange:()=>{}})));return{copied,exports,read:()=>desktopRecoveryStore.read()}}`},bundle:true,platform:'browser',format:'iife',write:false,tsconfig:'tsconfig.json'}).then(r=>r.outputFiles![0].text)
let browser:Browser;test.before(async()=>{browser=await chromium.launch({headless:true,...(process.env.XAANINK_TEST_CHROMIUM?{executablePath:process.env.XAANINK_TEST_CHROMIUM}:{})})});test.after(async()=>{await browser?.close()})
const item=(id:string,source:string,value:unknown)=>({id,source,path:'source',reason:'WORK_RESTORED',createdAt:'2026-10-08T00:00:00Z',value})
async function scenario(items:unknown[],run:(page:Page)=>Promise<void>){const page=await browser.newPage(),errors:string[]=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));try{await page.route('http://localhost/**',route=>route.fulfill({contentType:'text/html',body:'<div id="app"></div>'}));await page.goto('http://localhost/');await page.addStyleTag({content:css});await page.addScriptTag({content:await bundle});await page.evaluate(items=>{(window as any).f=(window as any).mount(items)},items);await page.getByRole('dialog').waitFor();await run(page);assert.deepEqual(errors,[])}finally{await page.close()}}
test('actual recovery dialog shows readable draft first, hides known idle records, and exports complete original data',()=>{
 const records=[item('idle','autosaves',{revision:0,status:'idle',pending:null,failed:null,inFlight:null,latest:null}),item('unknown','extension',{internalId:'not-for-ui',request:{url:'/never-send'}}),item('chat','chat',{active:{draft:'真正未发送的正文',pendingRequest:{body:'do not replay'}}})]
 return scenario(records,async page=>{assert.equal(await page.getByRole('navigation',{name:'恢复草稿列表'}).getByRole('button').count(),2);assert.equal(await page.getByText('作品恢复后的保留副本',{exact:true}).count(),2);assert.equal(await page.getByText('已关闭自动恢复',{exact:true}).count(),0);assert.equal(await page.getByLabel('保留的草稿内容').inputValue(),'对话草稿\n真正未发送的正文');await page.getByRole('button',{name:'复制内容',exact:true}).click();assert.deepEqual(await page.evaluate(()=>(window as any).f.copied),['对话草稿\n真正未发送的正文']);await page.getByRole('button',{name:'导出恢复草稿'}).click();await page.waitForFunction(()=>(window as any).f.exports.length===1);assert.deepEqual(await page.evaluate(()=>(window as any).f.exports[0].sources.recovery.items),records);assert.deepEqual(await page.evaluate(()=>(window as any).f.read().items),records)})
})
test('a long recovery preview explicitly marks truncation while export preserves every character',()=>scenario([item('long','chat',{draft:'字'.repeat(200000)})],async page=>{await page.getByText('预览仅显示前 100,000 个字符，完整内容可导出查看。',{exact:true}).waitFor();assert.equal((await page.getByLabel('保留的草稿内容').inputValue()).length,100000);await page.getByRole('button',{name:'复制预览',exact:true}).click();assert.equal(await page.evaluate(()=>(window as any).f.copied[0].length),100000);await page.getByRole('button',{name:'导出恢复草稿'}).click();await page.waitForFunction(()=>(window as any).f.exports.length===1);assert.equal(await page.evaluate(()=>(window as any).f.exports[0].sources.recovery.items[0].value.draft.length),200000)}))
test('an unknown record never exposes request metadata as prose and remains exportable',()=>scenario([item('unknown','extension',{request:{url:'/hidden-target',body:{prompt:'not a known draft'}}})],async page=>{assert.match(await page.getByLabel('保留的草稿内容').inputValue(),/完整内容已保留/);assert.equal(await page.getByRole('button',{name:'复制内容',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'导出恢复草稿'}).isEnabled(),true)}))
