import assert from 'node:assert/strict'
import {test} from 'node:test'
import {readFileSync,readdirSync} from 'node:fs'
import {build} from 'esbuild'
import {chromium,type Browser,type Page} from 'playwright-core'
import {ROOT_MIGRATION_LIMITS} from '../../desktop/core/root-inventory-limits'
const css=readdirSync('.next/static/chunks').filter(p=>p.endsWith('.css')).sort().map(p=>readFileSync('.next/static/chunks/'+p,'utf8')).join('\n')
const bundle=build({stdin:{loader:'tsx',resolveDir:process.cwd(),contents:`import React from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{RootMaintenanceScreen}from'./src/components/desktop/RootMaintenanceScreen';globalThis.mount=state=>{let receive;const commands=[];window.desktopMaintenance={state:async()=>state,subscribe:listener=>{receive=listener;return()=>{}},command:async name=>{commands.push(name)}};const root=createRoot(document.getElementById('app'));flushSync(()=>root.render(React.createElement(RootMaintenanceScreen)));return{commands,emit:s=>flushSync(()=>receive(s))}}`},bundle:true,platform:'browser',format:'iife',write:false,tsconfig:'tsconfig.json'}).then(r=>r.outputFiles![0].text)
let browser:Browser;test.before(async()=>{browser=await chromium.launch({headless:true,...(process.env.XAANINK_TEST_CHROMIUM?{executablePath:process.env.XAANINK_TEST_CHROMIUM}:{})})});test.after(async()=>{await browser?.close()})
const state=(items:string[]|null)=>({version:1,revision:1,phase:'cleanup-pending',theme:'paper',sourcePath:'/原目录',targetPath:'/新目录',copiedFiles:3,totalFiles:3,canCancel:false,canContinue:true,pendingCount:items?.length??3,pendingItems:items})
async function scenario(seed:unknown,run:(page:Page)=>Promise<void>){const page=await browser.newPage({viewport:{width:640,height:480}}),errors:string[]=[];page.setDefaultTimeout(1800);page.on('pageerror',e=>errors.push(e.message));try{await page.setContent('<div id="app"></div>');await page.addStyleTag({content:css});await page.addScriptTag({content:await bundle});await page.evaluate(seed=>{(window as any).f=(window as any).mount(seed)},seed);await run(page);assert.deepEqual(errors,[])}finally{await page.close()}}
test('actual maintenance UI makes every pending file reachable with pagination and translates status codes without executing paths',()=>{const items=Array.from({length:24},(_,n)=>`inbox/database/base/1/${n}`);items.push('NEW_ROOT_CHANGED');return scenario(state(items),async page=>{await page.getByText('查看 25 项待处理内容',{exact:true}).click();assert.equal(await page.getByRole('list',{name:'待处理明细'}).getByRole('listitem').count(),20);await page.getByRole('button',{name:'下一页',exact:true}).click();assert.equal(await page.getByRole('list',{name:'待处理明细'}).getByRole('listitem').count(),5);await page.getByText(items[23],{exact:true}).waitFor();await page.getByText('新目录已有后续修改，旧副本已保留。',{exact:true}).waitFor();assert.equal(await page.getByText('NEW_ROOT_CHANGED',{exact:true}).count(),0);await page.getByRole('button',{name:'返回工作台'}).click();assert.deepEqual(await page.evaluate(()=>(window as any).f.commands),['continue'])})})
test('unavailable details keep truthful count and valid authority, malformed later lists cannot erase the last valid list',()=>scenario(state(null),async page=>{await page.getByText('待处理明细暂不可用，原文件仍保留。',{exact:true}).waitFor();await page.evaluate(seed=>(window as any).f.emit(seed),{...state(['state.json']),revision:2});await page.getByText('查看 1 项待处理内容',{exact:true}).click();await page.getByText('state.json',{exact:true}).waitFor();await page.evaluate(seed=>(window as any).f.emit(seed),{...state(['forged']),revision:3,pendingCount:2});await page.getByRole('alert').waitFor();await page.getByText('state.json',{exact:true}).waitFor();assert.equal(await page.getByText('forged',{exact:true}).count(),0)}))

test('application history capacity is accepted by the real maintenance view, while overflow leaves the last state intact',()=>scenario({...state(null),pendingCount:ROOT_MIGRATION_LIMITS.pending},async page=>{await page.getByText('待处理明细暂不可用，原文件仍保留。',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'返回工作台'}).isEnabled(),true);await page.evaluate(seed=>(window as any).f.emit(seed),{...state(null),revision:2,pendingCount:ROOT_MIGRATION_LIMITS.pending+1});await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('button',{name:'返回工作台'}).isEnabled(),true)}))
