import assert from 'node:assert/strict'
import {test} from 'node:test'
import {readFile} from 'node:fs/promises'
import {build} from 'esbuild'
import {resolve} from 'node:path'
import {chromium,type Browser} from 'playwright-core'
// Actual Home and React. Only lazy leaf workbench/maintenance and next/dynamic
// loader wrapper are controlled; this does not test a Next export build.
const baseline=process.env.ROOT_RELOCATION_ROUTING_BASELINE==='1'
const bundle=build({stdin:{loader:'tsx',resolveDir:process.cwd(),contents:`import React from 'react';import {createRoot} from 'react-dom/client';import Home from './src/app/page';
globalThis.openEntry=(mode)=>{const initial={version:1,revision:1,phase:'blocked',theme:'paper',sourcePath:null,targetPath:null,notice:'pointer-invalid',unreadResultCount:null,canChoose:false,canCancel:false,canRestart:false};if(mode==='relocation'||mode==='both')window.desktopRootRelocation={state:async()=>initial,subscribe:()=>()=>{},command:async()=>{}};else delete window.desktopRootRelocation;if(mode==='maintenance'||mode==='both')window.desktopMaintenance={};else delete window.desktopMaintenance;createRoot(document.getElementById('app')).render(React.createElement(Home))};`},bundle:true,platform:'browser',format:'iife',write:false,tsconfig:'tsconfig.json',plugins:[{name:'controlled-lazy-leaves',setup(plugin){if(baseline)plugin.onLoad({filter:/src\/app\/page\.tsx$/},async()=>({loader:'tsx',resolveDir:resolve('src/app'),contents:await readFile('docs/evidence/implementation-33/home-before.tsx.txt','utf8')}));plugin.onResolve({filter:/^next\/dynamic$/},()=>({path:'lazy',namespace:'controlled'}));plugin.onResolve({filter:/^@\/components\/desktop\/(DesktopApp|RootMaintenanceScreen)$/},args=>({path:args.path.split('/').at(-1)!,namespace:'controlled'}));plugin.onLoad({filter:/.*/,namespace:'controlled'},args=>({loader:'js',resolveDir:process.cwd(),contents:args.path==='lazy'?`import React,{lazy,Suspense}from'react';export default loader=>{const Component=lazy(()=>loader().then(value=>({default:value.default??value})));return props=>React.createElement(Suspense,{fallback:null},React.createElement(Component,props))}`:args.path==='DesktopApp'?`import React from'react';export default function Workbench(){globalThis.workbenchMounts=(globalThis.workbenchMounts||0)+1;return React.createElement('div',{'data-entry':'workbench'},'controlled workbench')}`:`import React from'react';export function RootMaintenanceScreen(){globalThis.maintenanceMounts=(globalThis.maintenanceMounts||0)+1;return React.createElement('div',{'data-entry':'maintenance'},'controlled maintenance')}`}))}}]}).then(result=>result.outputFiles[0].text)
let browser:Browser
test.before(async()=>{browser=await chromium.launch({headless:true,...process.env.XAANINK_TEST_CHROMIUM?{executablePath:process.env.XAANINK_TEST_CHROMIUM}:{}})})
test.after(async()=>{await browser?.close()})
test('RH33-01 actual Home gives restricted relocation priority and never mounts workbench/maintenance leaves',async()=>{
 for(const mode of['relocation','both']){const page=await browser.newPage();try{await page.route('**/*',route=>route.request().isNavigationRequest()?route.fulfill({contentType:'text/html',body:'<div id="app"></div>'}):route.abort());await page.goto('http://127.0.0.1:1/restricted');await page.addScriptTag({content:await bundle});await page.evaluate(mode=>(window as any).openEntry(mode),mode);await page.getByRole('heading',{name:'定位原数据目录',exact:true}).waitFor({timeout:1500});assert.equal(await page.evaluate(()=>(globalThis as any).workbenchMounts??0),0);assert.equal(await page.evaluate(()=>(globalThis as any).maintenanceMounts??0),0)}finally{await page.close()}}
})
test('RH33-02 existing maintenance/ordinary routes remain reachable and build source includes only separate restricted preload',async()=>{
 for(const mode of['maintenance','ordinary']){const page=await browser.newPage();try{await page.route('**/*',route=>route.request().isNavigationRequest()?route.fulfill({contentType:'text/html',body:'<div id="app"></div>'}):route.abort());await page.goto('http://127.0.0.1:1/restricted');await page.addScriptTag({content:await bundle});await page.evaluate(mode=>(window as any).openEntry(mode),mode);await page.locator(`[data-entry="${mode==='ordinary'?'workbench':'maintenance'}"]`).waitFor({timeout:1500});assert.equal(await page.getByRole('heading',{name:'定位原数据目录',exact:true}).count(),0)}finally{await page.close()}}
 const script=await readFile('scripts/build-desktop.mjs','utf8');assert.match(script,/entryPoints:\s*\['desktop\/preload\/root-relocation.ts'\],\s*outfile:\s*'dist\/preload\/root-relocation.cjs'/)
})
