// Project resources and production dependency collection are separate in builder.
// Keep this list positive so author data, source and development evidence stay out.
module.exports = {
  appId: 'ink.xaanink.desktop',
  productName: '玄印写作',
  artifactName: 'XaanInk-${version}-${os}-${arch}.${ext}',
  directories: {output: 'release', buildResources: 'build'},
  asar: false,
  npmRebuild: false,
  forceCodeSigning: false,
  publish: null,
  files: [
    'dist/main/index.cjs',
    'dist/service/index.cjs',
    'dist/preload/index.cjs',
    'dist/preload/maintenance.cjs',
    'dist/preload/root-relocation.cjs',
    'out/**/*',
    'prisma/migrations/**/*',
    'LICENSE',
    'THIRD_PARTY_NOTICES.md',
    'runtime-licenses/**/*',
    '!**/*.map',
    '!**/node_modules/**/{test,tests,__tests__,example,examples}/**/*',
    '!**/node_modules/**/.bin/**/*',
    '!**/.env{,.*}',
    '!**/*.{db,db-shm,db-wal,sqlite,sqlite3,sqlite-shm,sqlite-wal,sqlite3-shm,sqlite3-wal}',
    '!**/PG_VERSION',
    '!out/**/{database,backups,.xuanxiang,.xuanxiang-storage,.xaanink,.xaanink-storage}/**/*',
  ],
  mac: {
    icon: 'build/icon.icns',
    category: 'public.app-category.productivity',
    identity: null,
    notarize: false,
    target: ['dmg', 'zip'],
  },
  dmg: {sign: false},
  win: {icon: 'build/icon.ico', target: ['nsis'], signAndEditExecutable: true, signExecutable: false},
  nsis: {oneClick: false, allowToChangeInstallationDirectory: true},
}
