import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,realpath,readFile,writeFile,readdir,rm,symlink,link,rename,mkdir} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import fsPromises from 'node:fs/promises'
import {syncBuiltinESMExports} from 'node:module'
import {VersionedStore} from '../../desktop/core/versioned-store'
import {directoryIdentity} from '../../desktop/core/root-ownership'
import {backupPlanSchema} from '../../desktop/shared/backup-plan'
import {WorkRestoreDraftBarrier} from '../../desktop/main/work-restore-draft-barrier'
import {validateApplicationMaintenanceMetadata,ApplicationMaintenanceMetadataError} from '../../desktop/service/database/application-maintenance-metadata'
const noop=()=>{}
const reject=(code:string)=>(error:unknown)=>error instanceof ApplicationMaintenanceMetadataError&&error.code===code&&!Object.hasOwn(error,'cause')
async function fixture(){const root=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-maintenance25-'))),directory=await directoryIdentity(root);return{root,directory,close:()=>rm(root,{recursive:true,force:true}),plan:join(root,'backup-plan.json'),barrier:join(root,'restore-draft-barrier.json')}}
async function plan(root:string,lastSuccess:number|null=1234){const store=new VersionedStore(join(root,'backup-plan.json'),{lastSuccess:null as number|null},value=>backupPlanSchema.parse(value));return store.update(0,{lastSuccess})}
async function pending(root:string){return new WorkRestoreDraftBarrier(root).begin({workId:randomUUID(),candidateId:randomUUID(),operationId:randomUUID()},async()=>{})}

test('MM25-01 absent optional maintenance files produce null and never create defaults or timers',async()=>{const f=await fixture();try{let checks=0;assert.deepEqual(await validateApplicationMaintenanceMetadata(f.directory,()=>{checks++}),{backupPlan:null,restoreBarrier:null});assert.deepEqual(await readdir(f.root),[]);assert.ok(checks>=2)}finally{await f.close()}})
test('MM25-02 original VersionedStore envelope and unknown pending barrier are read unchanged without activating or acknowledging',async()=>{const f=await fixture();try{const saved=await plan(f.root),active=await pending(f.root);await writeFile(join(f.root,'database.bin'),'original database');const before=await Promise.all([readFile(f.plan),readFile(f.barrier),readFile(join(f.root,'database.bin'))]);const result=await validateApplicationMaintenanceMetadata(f.directory,noop);assert.deepEqual(result,{backupPlan:saved,restoreBarrier:active});assert.deepEqual(await Promise.all([readFile(f.plan),readFile(f.barrier),readFile(join(f.root,'database.bin'))]),before);result.backupPlan!.value.lastSuccess=777;result.restoreBarrier!.outcome={status:'activated'};assert.deepEqual(await validateApplicationMaintenanceMetadata(f.directory,noop),{backupPlan:saved,restoreBarrier:active})}finally{await f.close()}})
test('MM25-03 null success and the largest safe revision retain original reader semantics including optional envelope annotations',async()=>{const f=await fixture();try{await writeFile(f.plan,JSON.stringify({schemaVersion:1,revision:Number.MAX_SAFE_INTEGER,value:{lastSuccess:null},annotation:'preserved not executed'}));assert.deepEqual(await validateApplicationMaintenanceMetadata(f.directory,noop),{backupPlan:{revision:Number.MAX_SAFE_INTEGER,value:{lastSuccess:null}},restoreBarrier:null});assert.equal(JSON.parse(await readFile(f.plan,'utf8')).annotation,'preserved not executed')}finally{await f.close()}})
test('MM25-04 malformed or incompatible backup envelope/value rejects with fixed code and preserves the original bytes',async()=>{const f=await fixture();try{for(const raw of ['{bad',JSON.stringify({schemaVersion:2,revision:1,value:{lastSuccess:0}}),JSON.stringify({schemaVersion:1,revision:-1,value:{lastSuccess:0}}),JSON.stringify({schemaVersion:1,revision:1.5,value:{lastSuccess:0}}),JSON.stringify({schemaVersion:1,revision:Number.MAX_SAFE_INTEGER+1,value:{lastSuccess:0}}),JSON.stringify({schemaVersion:1,revision:1,value:{lastSuccess:-1}}),JSON.stringify({schemaVersion:1,revision:1,value:{lastSuccess:'0'}}),JSON.stringify({schemaVersion:1,revision:1,value:{lastSuccess:null,run:true}})]){await writeFile(f.plan,raw);await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject('APPLICATION_MAINTENANCE_PLAN_INVALID'));assert.equal(await readFile(f.plan,'utf8'),raw)}}finally{await f.close()}})
test('MM25-05 malformed barrier is rejected by the original strict reader without altering a valid plan',async()=>{const f=await fixture();try{await plan(f.root);const original=await readFile(f.plan);for(const raw of ['{bad',JSON.stringify({schemaVersion:2,revision:1,active:null}),JSON.stringify({schemaVersion:1,revision:1,active:null,execute:true})]){await writeFile(f.barrier,raw);await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject('APPLICATION_MAINTENANCE_BARRIER_INVALID'));assert.equal(await readFile(f.barrier,'utf8'),raw);assert.deepEqual(await readFile(f.plan),original)}}finally{await f.close()}})
test('MM25-06 both optional files have an actual 16KiB read bound and do not become defaults on failure',async()=>{const f=await fixture();try{for(const name of ['backup-plan.json','restore-draft-barrier.json']){const path=join(f.root,name),bytes=Buffer.alloc(16385,32);await writeFile(path,bytes);await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject(name==='backup-plan.json'?'APPLICATION_MAINTENANCE_PLAN_INVALID':'APPLICATION_MAINTENANCE_BARRIER_INVALID'));assert.deepEqual(await readFile(path),bytes);await rm(path)}}finally{await f.close()}})
test('MM25-07 symlink or multi-link maintenance files preserve all foreign target bytes and fail closed',async()=>{const f=await fixture();try{const foreign=join(f.root,'foreign'),bytes=JSON.stringify({schemaVersion:1,revision:1,value:{lastSuccess:0}});await writeFile(foreign,bytes);for(const name of ['backup-plan.json','restore-draft-barrier.json'])for(const make of [symlink,link]){const path=join(f.root,name);await make(foreign,path);await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject(name==='backup-plan.json'?'APPLICATION_MAINTENANCE_PLAN_INVALID':'APPLICATION_MAINTENANCE_BARRIER_INVALID'));assert.equal(await readFile(foreign,'utf8'),bytes);await rm(path)}}finally{await f.close()}})
test('MM25-08 cancelled/expired host guard is sanitized, leaves bytes intact, and cannot return a valid snapshot',async()=>{const f=await fixture();try{await plan(f.root);const bytes=await readFile(f.plan);await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,()=>{throw Error('private-local-path-secret')}),reject('APPLICATION_MAINTENANCE_GUARD_REJECTED'));assert.deepEqual(await readFile(f.plan),bytes)}finally{await f.close()}})
test('MM25-09 replacing the application directory during awaited host validation never grants a foreign root',async()=>{const f=await fixture(),old=f.root+'-preserved';try{await plan(f.root);const before=await readFile(f.plan);let changed=false;await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,async()=>{if(!changed){changed=true;await rename(f.root,old);await mkdir(f.root);await writeFile(f.plan,JSON.stringify({schemaVersion:1,revision:1,value:{lastSuccess:0}}))}}),reject('APPLICATION_MAINTENANCE_DIRECTORY_CHANGED'));assert.deepEqual(await readFile(join(old,'backup-plan.json')),before)}finally{await f.close();await rm(old,{recursive:true,force:true})}})
test('MM25-10 a same-byte replacement during the real barrier inspect is rejected without claiming the new inode',async t=>{const f=await fixture();try{await pending(f.root);const original=WorkRestoreDraftBarrier.prototype.inspect;let moved=false;t.mock.method(WorkRestoreDraftBarrier.prototype,'inspect',async function(this:WorkRestoreDraftBarrier){const active=await original.call(this);if(!moved){moved=true;await rename(f.barrier,f.barrier+'.old');await writeFile(f.barrier,await readFile(f.barrier+'.old'))}return active});await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject('APPLICATION_MAINTENANCE_CHANGED'));assert.deepEqual(await readFile(f.barrier),await readFile(f.barrier+'.old'))}finally{await f.close()}})
test('MM25-11 an already-read backup plan cannot change while the original barrier reader is awaited',async t=>{const f=await fixture();try{await plan(f.root);const original=WorkRestoreDraftBarrier.prototype.inspect;t.mock.method(WorkRestoreDraftBarrier.prototype,'inspect',async function(this:WorkRestoreDraftBarrier){const active=await original.call(this);await writeFile(f.plan,JSON.stringify({schemaVersion:1,revision:2,value:{lastSuccess:999}}));return active});await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject('APPLICATION_MAINTENANCE_CHANGED'));assert.equal(JSON.parse(await readFile(f.plan,'utf8')).revision,2)}finally{await f.close()}})
test('MM25-12 a file appearing after an absent observation is not silently treated as an empty plan',async t=>{const f=await fixture();try{const original=WorkRestoreDraftBarrier.prototype.inspect;t.mock.method(WorkRestoreDraftBarrier.prototype,'inspect',async function(this:WorkRestoreDraftBarrier){const active=await original.call(this);await plan(f.root);return active});await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject('APPLICATION_MAINTENANCE_CHANGED'));assert.equal(JSON.parse(await readFile(f.plan,'utf8')).value.lastSuccess,1234)}finally{await f.close()}})
test('MM25-13 invalid UTF8 in otherwise valid envelope annotations or a failed barrier message is rejected instead of inventing replacement text',async()=>{const f=await fixture();try{for(const name of ['backup-plan.json','restore-draft-barrier.json']){const source=name==='backup-plan.json'?{schemaVersion:1,revision:1,value:{lastSuccess:0},annotation:'UTF8_MARKER'}:{schemaVersion:1,revision:1,active:{token:randomUUID(),workId:randomUUID(),candidateId:randomUUID(),createdAt:'2026-10-08T00:00:00.000Z',outcome:{status:'failed',message:'UTF8_MARKER'}}},[prefix,suffix]=JSON.stringify(source).split('UTF8_MARKER'),bytes=Buffer.concat([Buffer.from(prefix),Buffer.from([0xc3,0x28]),Buffer.from(suffix)]);await writeFile(join(f.root,name),bytes);await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,noop),reject(name==='backup-plan.json'?'APPLICATION_MAINTENANCE_PLAN_INVALID':'APPLICATION_MAINTENANCE_BARRIER_INVALID'));assert.deepEqual(await readFile(join(f.root,name)),bytes);await rm(join(f.root,name))}}finally{await f.close()}})
test('MM25-14 settled restore results and legacy pending without operationId remain inert metadata, not replayable work',async()=>{const f=await fixture();try{const barrier=new WorkRestoreDraftBarrier(f.root),active=await barrier.begin({workId:randomUUID(),candidateId:randomUUID()},async()=>{});for(const outcome of [{status:'pending' as const},{status:'activated' as const},{status:'failed' as const,message:'原库保持原样'}]){const value={...active,outcome};delete value.operationId;await writeFile(f.barrier,JSON.stringify({schemaVersion:1,revision:3,active:value}));const before=await readFile(f.barrier);assert.deepEqual((await validateApplicationMaintenanceMetadata(f.directory,noop)).restoreBarrier,value);assert.deepEqual(await readFile(f.barrier),before)}}finally{await f.close()}})
test('MM25-15 an expired host during the final real root lstat cannot approve maintenance metadata',async t=>{const f=await fixture();let valid=true,armed=false;const originalInspect=WorkRestoreDraftBarrier.prototype.inspect,originalLstat=fsPromises.lstat;try{
 await plan(f.root);const before=await readFile(f.plan)
 t.mock.method(WorkRestoreDraftBarrier.prototype,'inspect',async function(this:WorkRestoreDraftBarrier){const result=await originalInspect.call(this);armed=true;return result})
 const mocked=t.mock.method(fsPromises,'lstat',async(...args:Parameters<typeof fsPromises.lstat>)=>{const result=await originalLstat(...args);if(armed&&args[0]===f.root){armed=false;valid=false}return result});syncBuiltinESMExports();t.after(()=>{mocked.mock.restore();syncBuiltinESMExports()})
 await assert.rejects(validateApplicationMaintenanceMetadata(f.directory,()=>{if(!valid)throw Error('expired close owner')}),reject('APPLICATION_MAINTENANCE_GUARD_REJECTED'));assert.deepEqual(await readFile(f.plan),before)
 }finally{await f.close()}})
