import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,mkdir,realpath,rm,writeFile,readFile,readdir,link,symlink,rename} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {DraftJournal} from '../../desktop/main/draft-journal'
import {directoryIdentity} from '../../desktop/core/root-ownership'
import {prepareApplicationDraftRetention,validateApplicationDraftRetentionProof,persistApplicationDraftRetention,validatePersistedApplicationDraftRetention,ApplicationRestoreDraftError} from '../../desktop/core/application-restore-drafts'
import {applicationDraftRetentionSchema} from '../../desktop/shared/application-restore'
import {canonical,digest} from '../../desktop/core/application-backup-files'
import type {DraftSnapshot} from '../../desktop/shared/drafts'
const now='2026-10-08T00:00:00.000Z',noop=()=>{}
function snapshot(value:string):DraftSnapshot{return{version:1,revision:1,createdAt:now,autosaves:[],sources:{chat:{queuedRequests:[{prompt:value,sent:false}],draft:value}},issues:[]}}
async function fixture(){const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-application-drafts35-'))),appId=randomUUID(),current=join(base,'current'),backup=join(base,'backup');for(const path of[current,backup]){await mkdir(path);await writeFile(join(path,'xuanxiang-app.json'),JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:appId,phase:'ready',inboxReady:true}))}const input={appId,operationId:randomUUID(),candidateId:randomUUID(),current:await directoryIdentity(current),backup:await directoryIdentity(backup)};return{base,current,backup,input,async persist(root:string,value:string){const journal=new DraftJournal(root);const owner=randomUUID();journal.activate(owner);await journal.persist(owner,snapshot(value))},close:()=>rm(base,{recursive:true,force:true})}}
const error=(code?:string)=>(cause:unknown)=>cause instanceof ApplicationRestoreDraftError&&(!code||cause.code===code)&&!Object.hasOwn(cause,'cause')
test('AD35-01 actual current and backup journals stay separate inert copies without any source write',async()=>{const f=await fixture();try{await f.persist(f.current,'latest author input');await f.persist(f.backup,'old backup queued request');const before=await Promise.all([readFile(join(f.current,'drafts.json')),readFile(join(f.backup,'drafts.json'))]),proof=await prepareApplicationDraftRetention(f.input,noop);proof.assertCurrent();const value=applicationDraftRetentionSchema.parse(proof.retention);assert.equal(value.type,'application');assert.equal(value.reason,'APPLICATION_RESTORED');assert.deepEqual(value.snapshots.map(row=>[row.origin,row.snapshot]),[['current',snapshot('latest author input')],['backup',snapshot('old backup queued request')]]);assert.deepEqual(await Promise.all([readFile(join(f.current,'drafts.json')),readFile(join(f.backup,'drafts.json'))]),before);assert.deepEqual(await readdir(f.current),['drafts.json','xuanxiang-app.json'])}finally{await f.close()}})
test('AD35-02 genuinely absent journals are null data and never create defaults',async()=>{const f=await fixture();try{const proof=await prepareApplicationDraftRetention(f.input,noop);assert.equal(proof.retention.snapshots.length,0);assert.deepEqual(await readdir(f.current),['xuanxiang-app.json']);assert.deepEqual(await readdir(f.backup),['xuanxiang-app.json']);proof.assertCurrent()}finally{await f.close()}})
test('AD35-03 broken checksum, overlarge, symlink or hardlinked draft rejects and preserves foreign bytes',async()=>{for(const kind of['checksum','oversize','symlink','hardlink']){const f=await fixture();try{await f.persist(f.current,'original');const path=join(f.current,'drafts.json');if(kind==='checksum'){const value=JSON.parse(await readFile(path,'utf8'));value.digest='0'.repeat(64);await writeFile(path,JSON.stringify(value))}if(kind==='oversize')await writeFile(path,Buffer.alloc(16*1024*1024+65537,32));if(kind==='symlink'){await rename(path,join(f.base,'foreign'));await symlink(join(f.base,'foreign'),path)}if(kind==='hardlink')await link(path,join(f.base,'foreign'));const before=await readFile(path);await assert.rejects(prepareApplicationDraftRetention(f.input,noop),error('APPLICATION_DRAFT_INVALID'));assert.deepEqual(await readFile(path),before)}finally{await f.close()}}})
test('AD35-04 wrong application marker and expired host fail with fixed code before granting a draft proof',async()=>{const f=await fixture();try{await assert.rejects(prepareApplicationDraftRetention(f.input,()=>{throw Error('/private/key/secret')}),error('APPLICATION_DRAFT_OWNER_EXPIRED'));await writeFile(join(f.backup,'xuanxiang-app.json'),JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:randomUUID(),phase:'ready',inboxReady:true}));await assert.rejects(prepareApplicationDraftRetention(f.input,noop),error('APPLICATION_DRAFT_APP_MISMATCH'));assert.deepEqual(await readdir(f.current),['xuanxiang-app.json'])}finally{await f.close()}})
test('AD35-05 final synchronous proof rejects a late same-byte inode replacement and preserves it',async()=>{const f=await fixture();try{await f.persist(f.current,'author');const proof=await prepareApplicationDraftRetention(f.input,noop),path=join(f.current,'drafts.json'),before=await readFile(path);await rename(path,path+'.old');await writeFile(path,before);assert.throws(()=>proof.assertCurrent(),error('APPLICATION_DRAFT_CHANGED'));assert.deepEqual(await readFile(path),before)}finally{await f.close()}})
test('AD35-06 final proof rejects a journal appearing after an absent observation',async()=>{const f=await fixture();try{const proof=await prepareApplicationDraftRetention(f.input,noop);await f.persist(f.backup,'late backup');assert.throws(()=>proof.assertCurrent(),error('APPLICATION_DRAFT_CHANGED'));assert.equal(JSON.parse(await readFile(join(f.backup,'drafts.json'),'utf8')).snapshot.sources.chat.draft,'late backup')}finally{await f.close()}})
test('AD35-07 combined original snapshot capacity blocks without truncation or losing either draft',async()=>{const f=await fixture();try{await f.persist(f.current,'A'.repeat(4.5*1024*1024));await f.persist(f.backup,'B'.repeat(4.5*1024*1024));await assert.rejects(prepareApplicationDraftRetention(f.input,noop),error('APPLICATION_DRAFT_CAPACITY'));assert.equal(JSON.parse(await readFile(join(f.current,'drafts.json'),'utf8')).snapshot.sources.chat.draft.length,4.5*1024*1024);assert.equal(JSON.parse(await readFile(join(f.backup,'drafts.json'),'utf8')).snapshot.sources.chat.draft.length,4.5*1024*1024)}finally{await f.close()}})

test('AD35-08 unavailable latest root is explicit data, never claimed as an empty healthy journal',async()=>{const f=await fixture();try{await f.persist(f.backup,'backup draft');const proof=await prepareApplicationDraftRetention({...f.input,current:null},noop);assert.equal((proof.retention as any).currentRootAvailable,false);assert.equal(proof.retention.snapshots.length,1);assert.equal(proof.retention.snapshots[0].origin,'backup');assert.deepEqual(await readdir(f.current),['xuanxiang-app.json'])}finally{await f.close()}})
test('AD35-09 previous retained snapshots preserve provenance and merge only complete equal ids without recursive bundles',async()=>{const f=await fixture();try{await f.persist(f.current,'latest');await f.persist(f.backup,'old');const first=(await prepareApplicationDraftRetention(f.input,noop)).retention;for(const path of[f.current,f.backup]){await writeFile(join(path,'application-restore-drafts.json'),JSON.stringify(first));await rm(join(path,'drafts.json'))}const next=await prepareApplicationDraftRetention({...f.input,operationId:randomUUID(),candidateId:randomUUID()},noop);assert.equal(next.retention.snapshots.length,2);assert.deepEqual(next.retention.snapshots,first.snapshots);assert.equal(JSON.stringify(next.retention).includes('xuanxiang-application-draft-retention'),true);assert.equal(next.retention.snapshots.some(row=>Object.hasOwn(row.snapshot,'retention')),false);next.assertCurrent()}finally{await f.close()}})
test('AD35-10 valid but conflicting previous entries with the same id reject rather than discard either author copy',async()=>{const f=await fixture();try{await f.persist(f.current,'original author');const first=(await prepareApplicationDraftRetention(f.input,noop)).retention,{checksum,...body}=first,changed={...body,snapshots:body.snapshots.map(row=>({...row,snapshot:snapshot('different author bytes')}))},foreign={...changed,checksum:digest(canonical(changed))};await writeFile(join(f.current,'application-restore-drafts.json'),JSON.stringify(first));await writeFile(join(f.backup,'application-restore-drafts.json'),JSON.stringify(foreign));const original=await readFile(join(f.current,'application-restore-drafts.json')),other=await readFile(join(f.backup,'application-restore-drafts.json'));await assert.rejects(prepareApplicationDraftRetention(f.input,noop),error('APPLICATION_DRAFT_HISTORY_CONFLICT'));assert.deepEqual(await readFile(join(f.current,'application-restore-drafts.json')),original);assert.deepEqual(await readFile(join(f.backup,'application-restore-drafts.json')),other)}finally{await f.close()}})

test('AD35-11 only the actual issued draft proof is valid, never raw cloned fields or a forged no-op seal',async()=>{const f=await fixture();try{await f.persist(f.current,'latest');const proof=await prepareApplicationDraftRetention(f.input,noop),expected={appId:f.input.appId,operationId:f.input.operationId,candidateId:f.input.candidateId,backup:f.input.backup};assert.deepEqual(validateApplicationDraftRetentionProof(proof,expected),proof.retention);for(const forged of[{retention:structuredClone(proof.retention),assertCurrent(){}},{...proof}])assert.throws(()=>validateApplicationDraftRetentionProof(forged,expected),error('APPLICATION_DRAFT_PROOF_INVALID'))}finally{await f.close()}})
test('AD35-12 issued data capability cannot be retargeted to another candidate or bypass a replaced seal',async()=>{const f=await fixture();try{const proof=await prepareApplicationDraftRetention(f.input,noop),expected={appId:f.input.appId,operationId:f.input.operationId,candidateId:f.input.candidateId,backup:f.input.backup};assert.throws(()=>validateApplicationDraftRetentionProof(proof,{...expected,candidateId:randomUUID()}),error('APPLICATION_DRAFT_PROOF_INVALID'));proof.assertCurrent=()=>{};await f.persist(f.backup,'late');assert.throws(()=>validateApplicationDraftRetentionProof(proof,expected),error('APPLICATION_DRAFT_CHANGED'))}finally{await f.close()}})
test('AD35-13 modifying valid returned DTO data cannot become a producer-authorized retention bundle',async()=>{const f=await fixture();try{await f.persist(f.current,'actual');const proof=await prepareApplicationDraftRetention(f.input,noop);proof.retention.snapshots[0].snapshot=snapshot('forged');const{checksum,...body}=proof.retention;proof.retention.checksum=digest(canonical(body));assert.throws(()=>validateApplicationDraftRetentionProof(proof,{appId:f.input.appId,operationId:f.input.operationId,candidateId:f.input.candidateId,backup:f.input.backup}),error('APPLICATION_DRAFT_PROOF_INVALID'));assert.equal(JSON.parse(await readFile(join(f.current,'drafts.json'),'utf8')).snapshot.sources.chat.draft,'actual')}finally{await f.close()}})

// The fixed artifact is written by the same issuing module; raw StoredFile or
// replacement callbacks cannot grant an arbitrary rebase of source evidence.
test('AD35-14 own retention write preserves both original journals and returns a fresh sealed data proof',async()=>{const f=await fixture();try{await f.persist(f.current,'latest');await f.persist(f.backup,'old');const original=await Promise.all([readFile(join(f.current,'drafts.json')),readFile(join(f.backup,'drafts.json'))]),proof=await prepareApplicationDraftRetention(f.input,noop),saved=await persistApplicationDraftRetention(proof,{appId:f.input.appId,operationId:f.input.operationId,candidateId:f.input.candidateId,backup:f.input.backup});assert.deepEqual(validatePersistedApplicationDraftRetention(saved),proof.retention);assert.equal(saved.file.path,'application-restore-drafts.json');assert.deepEqual(JSON.parse(await readFile(join(f.backup,saved.file.path),'utf8')),proof.retention);assert.deepEqual(await Promise.all([readFile(join(f.current,'drafts.json')),readFile(join(f.backup,'drafts.json'))]),original);assert.throws(()=>proof.assertCurrent(),error('APPLICATION_DRAFT_CHANGED'));saved.assertCurrent()}finally{await f.close()}})
test('AD35-15 persisted proof detects foreign replacement and still checks latest original draft',async()=>{const f=await fixture();try{await f.persist(f.current,'latest');const proof=await prepareApplicationDraftRetention(f.input,noop),saved=await persistApplicationDraftRetention(proof,{appId:f.input.appId,operationId:f.input.operationId,candidateId:f.input.candidateId,backup:f.input.backup}),path=join(f.backup,saved.file.path),bytes=await readFile(path);await rename(path,path+'.foreign');await writeFile(path,bytes);assert.throws(()=>validatePersistedApplicationDraftRetention(saved),error('APPLICATION_DRAFT_CHANGED'));assert.deepEqual(await readFile(path),bytes)}finally{await f.close()}const second=await fixture();try{const saved=await persistApplicationDraftRetention(await prepareApplicationDraftRetention(second.input,noop),{appId:second.input.appId,operationId:second.input.operationId,candidateId:second.input.candidateId,backup:second.input.backup});await second.persist(second.current,'late latest');saved.assertCurrent=()=>{};assert.throws(()=>validatePersistedApplicationDraftRetention(saved),error('APPLICATION_DRAFT_CHANGED'))}finally{await second.close()}})
test('AD35-16 fabricated or mutated draft data never writes a candidate retention artifact',async()=>{const f=await fixture();try{const proof=await prepareApplicationDraftRetention(f.input,noop),expected={appId:f.input.appId,operationId:f.input.operationId,candidateId:f.input.candidateId,backup:f.input.backup};await assert.rejects(persistApplicationDraftRetention({...proof},expected),error('APPLICATION_DRAFT_PROOF_INVALID'));assert.deepEqual(await readdir(f.backup),['xuanxiang-app.json']);const saved=await persistApplicationDraftRetention(proof,expected);assert.throws(()=>validatePersistedApplicationDraftRetention({...saved}),error('APPLICATION_DRAFT_PROOF_INVALID'));saved.retention.currentRootAvailable=false;assert.throws(()=>validatePersistedApplicationDraftRetention(saved),error('APPLICATION_DRAFT_PROOF_INVALID'))}finally{await f.close()}})
