import assert from 'node:assert/strict'
import {test,type TestContext} from 'node:test'
import {mkdtemp,mkdir,realpath,rm,writeFile,readFile,readdir} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {PGlite} from '@electric-sql/pglite'
import {ApplicationBackups} from '../../desktop/core/application-backups'
import {DataRootManager} from '../../desktop/core/data-root'
import {directoryIdentity} from '../../desktop/core/root-ownership'
import {prepareApplicationDraftRetention} from '../../desktop/core/application-restore-drafts'
import {prepareApplicationRestoreWithProof,reSealApplicationRestoreWithProof,validatePreparedApplicationRestoreForActivation,type ApplicationRestoreHost,type PreparedApplicationRestoreProof} from '../../desktop/service/database/application-restore'
import {ApplicationRestoreActivation,ApplicationRestoreActivationError} from '../../desktop/core/application-restore-activation'
import {DraftJournal} from '../../desktop/main/draft-journal'

// Actual private issuance and filesystem ownership are tested with a declared
// SQL protocol double. These cases confer no PG/schema health or native UI PASS.
async function fixture(t:TestContext){
 let engines=0,live=true,revokeAtClose=false
 t.mock.method(PGlite,'create',async()=>{engines++;return{async query(sql:string){return{rows:sql==='SHOW server_version'?[{server_version:'18.0'}]:sql==='SELECT id FROM "User"'?[{id:'local-author'}]:sql.startsWith('SELECT count(*)::int AS n')?[{n:0}]:[]}},async exec(){},async close(){if(revokeAtClose)live=false},async transaction<T>(run:(tx:unknown)=>Promise<T>){return run(this)}} as unknown as PGlite})
 const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-owner35-'))),source=join(base,'source'),storage=join(base,'packages'),parent=join(base,'parent'),boot=join(base,'boot'),appId=randomUUID()
 for(const path of[source,storage,parent,boot])await mkdir(path)
 await mkdir(join(source,'inbox/database'),{recursive:true});await writeFile(join(source,'inbox/database/PG_VERSION'),'18')
 await writeFile(join(source,'xuanxiang-app.json'),JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:appId,phase:'ready',inboxReady:true}));await writeFile(join(source,'catalog.json'),JSON.stringify({schemaVersion:1,revision:0,value:[]}))
 const root=await directoryIdentity(source),selectedParent=await directoryIdentity(parent),backups=new ApplicationBackups(await directoryIdentity(storage),appId,{pglite:'protocol-double',postgresMajor:18},{assertOwner(){},assertClosed(){},async verifyCaptured(){}}),selected=await backups.create(root,10)
 await new DataRootManager(boot,source).adopt(root)
 const host:ApplicationRestoreHost={expectedAppId:appId,async assertOwner(){},assertOwnerImmediately(directory){assert.deepEqual(directory,selectedParent);if(!live)throw Error('private fixture native owner revoked')}}
 return{base,boot,root,parent,host,backups,selected,engines:()=>engines,revoke:()=>{live=false},revokeOnClose:()=>{revokeAtClose=true},prepare:()=>prepareApplicationRestoreWithProof(backups,selected.id,selectedParent,[],host),async reseal(prepared:PreparedApplicationRestoreProof){return reSealApplicationRestoreWithProof(prepared,await prepareApplicationDraftRetention({appId,operationId:randomUUID(),candidateId:prepared.candidate.id,current:root,backup:prepared.candidate.directory},()=>{}))},bootstrap:await directoryIdentity(boot),close:()=>rm(base,{recursive:true,force:true})}
}
const code=(expected:string)=>(cause:unknown)=>cause instanceof Error&&cause.message===expected&&!Object.hasOwn(cause,'cause')
test('AN35-01 a Promise native owner assertion is rejected before any producer directory mutation or engine open',async t=>{const f=await fixture(t);try{f.host.assertOwnerImmediately=(()=>Promise.resolve()) as unknown as (typeof f.host)['assertOwnerImmediately'];await assert.rejects(f.prepare(),code('APPLICATION_RESTORE_OWNER_EXPIRED'));assert.equal(f.engines(),0);assert.deepEqual(await readdir(f.parent),[])}finally{await f.close()}})
test('AN35-02 legacy candidate-only owner cannot authorize batch35 reseal by adding a new callback after issuance',async t=>{const f=await fixture(t);try{delete f.host.assertOwnerImmediately;const prepared=await f.prepare(),metadata=join(prepared.candidate.directory.path,'.xuanxiang-application-candidate.json'),before=await readFile(metadata);f.host.assertOwnerImmediately=()=>{};await assert.rejects(f.reseal(prepared),code('APPLICATION_RESTORE_OWNER_SEAL_REQUIRED'));assert.equal(f.engines(),1);assert.deepEqual(await readFile(metadata),before);await assert.rejects(readFile(join(prepared.candidate.directory.path,'application-restore-drafts.json')),cause=>(cause as NodeJS.ErrnoException).code==='ENOENT')}finally{await f.close()}})
test('AN35-03 native parent revocation during the final closed-engine await never issues a new activation grant',async t=>{const f=await fixture(t);try{const prepared=await f.prepare(),metadata=join(prepared.candidate.directory.path,'.xuanxiang-application-candidate.json'),before=await readFile(metadata);f.revokeOnClose();await assert.rejects(f.reseal(prepared));assert.equal(f.engines(),2);assert.deepEqual(await readFile(metadata),before);assert.throws(()=>validatePreparedApplicationRestoreForActivation(prepared),code('APPLICATION_RESTORE_PROOF_INVALID'));assert.ok((await readFile(join(prepared.candidate.directory.path,'application-restore-drafts.json'))).length>0)}finally{await f.close()}})
test('AN35-04 revocation after asynchronous native confirmation still blocks the exact pointer CAS and keeps all source bytes',async t=>{const f=await fixture(t);try{const proof=await f.reseal(await f.prepare()),pointer=await readFile(join(f.boot,'data-root.json')),activation=new ApplicationRestoreActivation(f.bootstrap,{assertStableLock(){},assertCold(){},assertOwner(){},async confirm(){await Promise.resolve();f.revoke();f.host.assertOwnerImmediately=()=>{};return true}}),preview=await activation.prepare('owner',proof,{currentRootAvailable:true,beforeSnapshot:{backups:f.backups,backupId:f.selected.id}});await assert.rejects(activation.activate('owner',preview.operationId),cause=>cause instanceof ApplicationRestoreActivationError&&!Object.hasOwn(cause,'cause'));assert.deepEqual(await readFile(join(f.boot,'data-root.json')),pointer);assert.deepEqual(await readdir(f.boot),['data-root.json']);assert.ok((await readFile(join(f.root.path,'xuanxiang-app.json'))).length>0)}finally{await f.close()}})
test('AN35-05 a later valid snapshot of changed source drafts cannot relabel an older retained source copy as the latest authoritative draft',async t=>{const f=await fixture(t);try{const proof=await f.reseal(await f.prepare()),journal=new DraftJournal(f.root.path);journal.activate('later');await journal.persist('later',{version:1,revision:1,createdAt:'2026-10-08T00:00:00.000Z',autosaves:[],sources:{chat:{draft:'changed after candidate draft preservation'}},issues:[]});const latest=await f.backups.create(f.root,10),pointer=await readFile(join(f.boot,'data-root.json')),changed=await readFile(join(f.root.path,'drafts.json')),activation=new ApplicationRestoreActivation(f.bootstrap,{assertStableLock(){},assertCold(){},assertOwner(){},async confirm(){return true}});await assert.rejects(activation.prepare('owner',proof,{currentRootAvailable:true,beforeSnapshot:{backups:f.backups,backupId:latest.id}}),cause=>cause instanceof ApplicationRestoreActivationError&&!Object.hasOwn(cause,'cause'));assert.deepEqual(await readFile(join(f.boot,'data-root.json')),pointer);assert.deepEqual(await readFile(join(f.root.path,'drafts.json')),changed);assert.deepEqual(await readdir(f.boot),['data-root.json'])}finally{await f.close()}})
