import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,mkdir,realpath,rm,writeFile,readFile} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {directoryIdentity,hashRegular} from '../../desktop/core/root-ownership'
import {inspectTree,assertTreeImmediately} from '../../desktop/core/application-backup-files'
import {inspectClosedApplicationSnapshotSource} from '../../desktop/core/application-restore-source'
test('AS35-01 source matching performs only two complete candidate seals, preserving exact source bytes and final full-tree oracle',async()=>{const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-source35-'))),source=join(base,'source'),candidate=join(base,'candidate');try{await mkdir(source);await mkdir(candidate);const files=[];for(let i=0;i<12;i++){const path=`file-${i}.json`;await writeFile(join(source,path),JSON.stringify({draft:i}));await writeFile(join(candidate,path),JSON.stringify({draft:i}));const observed=await hashRegular(join(source,path));files.push({path,size:observed.size,sha256:observed.sha256})}const root=await directoryIdentity(source),target=await directoryIdentity(candidate),tree=await inspectTree(target,()=>{});let seals=0,reads=0;const matched=await inspectClosedApplicationSnapshotSource(root,files,()=>{reads++},()=>{seals++;assertTreeImmediately(target,tree)});assert.equal(matched.length,12);assert.equal(seals,2);assert.ok(reads>=12);for(const file of matched)assert.equal(file.sha256,(await hashRegular(join(source,file.path))).sha256)}finally{await rm(base,{recursive:true,force:true})}})
test('AS35-02 candidate addition during asynchronous source IO is rejected by final original tree, never recaptured as healthy',async()=>{const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-source35-'))),source=join(base,'source'),candidate=join(base,'candidate');try{await mkdir(source);await mkdir(candidate);await writeFile(join(source,'source.json'),'latest author input');await writeFile(join(candidate,'candidate.json'),'sealed');const root=await directoryIdentity(source),target=await directoryIdentity(candidate),tree=await inspectTree(target,()=>{}),file=await hashRegular(join(source,'source.json'));let calls=0;await assert.rejects(inspectClosedApplicationSnapshotSource(root,[{path:'source.json',size:file.size,sha256:file.sha256}],async()=>{if(++calls===2)await writeFile(join(candidate,'foreign.json'),'foreign candidate bytes')},()=>assertTreeImmediately(target,tree)));assert.equal(await readFile(join(candidate,'foreign.json'),'utf8'),'foreign candidate bytes');assert.equal(await readFile(join(source,'source.json'),'utf8'),'latest author input')}finally{await rm(base,{recursive:true,force:true})}})
