import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,mkdir,realpath,rm,writeFile,readFile,readdir} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {directoryIdentity} from '../../desktop/core/root-ownership'
import {ApplicationRestoreActivation,ApplicationRestoreActivationError} from '../../desktop/core/application-restore-activation'
import type {PreparedApplicationRestoreProof} from '../../desktop/service/database/application-restore'
async function fixture(){const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-activation35-'))),boot=join(base,'boot'),root=join(base,'root'),target=join(base,'target'),appId=randomUUID();for(const path of[boot,root,target])await mkdir(path);await writeFile(join(root,'xuanxiang-app.json'),JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:appId,phase:'ready',inboxReady:true}));const pointer={schemaVersion:1 as const,revision:1,rootId:appId,migrationId:null,root:await directoryIdentity(root)};await writeFile(join(boot,'data-root.json'),JSON.stringify(pointer)+'\n');const owner=randomUUID(),raw:PreparedApplicationRestoreProof={candidate:{format:'xuanxiang-application-candidate',schemaVersion:1,id:randomUUID(),appId,backupId:randomUUID(),backupChecksum:'0'.repeat(64),createdAt:new Date().toISOString(),phase:'ready',directory:await directoryIdentity(target),engine:{pglite:'0.5.8',postgresMajor:17},migrations:[],files:[],directories:[],checksum:'0'.repeat(64),activation:{operationId:randomUUID(),initialChecksum:'0'.repeat(64),retentionChecksum:'0'.repeat(64),barrierToken:randomUUID()}},tree:{files:[],directories:[]}};return{base,boot,owner,raw,bootstrap:await directoryIdentity(boot),close:()=>rm(base,{recursive:true,force:true})}}
test('AA35-F01 raw, cloned and foreign-prototype candidate DTOs cannot grant pointer activation',async()=>{for(const kind of['raw','clone','prototype']){const f=await fixture();try{let confirms=0;const activation=new ApplicationRestoreActivation(f.bootstrap,{assertStableLock(){},assertCold(){},assertOwner(){},async confirm(){confirms++;return true}}),before=await readFile(join(f.boot,'data-root.json')),candidate=kind==='clone'?JSON.parse(JSON.stringify(f.raw)):kind==='prototype'?Object.assign(Object.create({issuer:true}),f.raw):f.raw;await assert.rejects(activation.prepare(f.owner,candidate,{currentRootAvailable:true,beforeSnapshot:null}),error=>error instanceof ApplicationRestoreActivationError&&error.code==='APPLICATION_RESTORE_PROOF_INVALID'&&!error.cause);assert.equal(confirms,0);assert.deepEqual(await readFile(join(f.boot,'data-root.json')),before);assert.deepEqual(await readdir(f.boot),['data-root.json'])}finally{await f.close()}}})
test('AA35-F02 synchronous cold owner/lock proof cannot be replaced by a Promise or leak host errors',async()=>{for(const kind of['lock','cold','owner','promise']){const f=await fixture();try{const options={assertStableLock(){if(kind==='lock')throw Error('/private/key')},assertCold(){if(kind==='cold')throw Error('/private/key')},assertOwner(){if(kind==='owner')throw Error('/private/key');if(kind==='promise')return Promise.resolve() as unknown as void},async confirm(){return true}},activation=new ApplicationRestoreActivation(f.bootstrap,options);await assert.rejects(activation.prepare(f.owner,f.raw,{currentRootAvailable:true,beforeSnapshot:null}),error=>error instanceof ApplicationRestoreActivationError&&error.code===({lock:'LOCK_REQUIRED',cold:'SOURCE_NOT_CLOSED',owner:'OWNER_EXPIRED',promise:'OWNER_EXPIRED'}as const)[kind]&&!error.cause);assert.deepEqual(await readdir(f.boot),['data-root.json'])}finally{await f.close()}}})
