import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,mkdir,realpath,rm,writeFile,readFile,rename} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {directoryIdentity} from '../../desktop/core/root-ownership'
import {DraftJournal} from '../../desktop/main/draft-journal'
import {prepareApplicationDraftRetention,persistApplicationDraftRetention,installInertApplicationDraftJournal} from '../../desktop/core/application-restore-drafts'
import {ApplicationRestoreDraftBarrier,ApplicationRestoreDraftBarrierError} from '../../desktop/main/application-restore-draft-barrier'
import {applicationDraftRecoveryItems} from '../../desktop/shared/application-restore'
async function fixture(options:{beforeRename?():Promise<void>;withWrite?<T>(run:()=>Promise<T>):Promise<T>}={}){const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-appbarrier35-'))),current=join(base,'current'),backup=join(base,'backup'),appId=randomUUID();for(const root of[current,backup]){await mkdir(root);await writeFile(join(root,'xuanxiang-app.json'),JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:appId,phase:'ready',inboxReady:true}));const journal=new DraftJournal(root);journal.activate('original');await journal.persist('original',{version:1,revision:1,createdAt:'2026-10-08T00:00:00.000Z',autosaves:[],sources:{chat:{draft:root===current?'latest':'old',queuedRequests:[{approved:true,prompt:'never replay'}]}},issues:[]})}const input={appId,operationId:randomUUID(),candidateId:randomUUID(),current:await directoryIdentity(current),backup:await directoryIdentity(backup)},proof=await prepareApplicationDraftRetention(input,()=>{}),saved=await installInertApplicationDraftJournal(await persistApplicationDraftRetention(proof,{appId,operationId:input.operationId,candidateId:input.candidateId,backup:input.backup})),journal=new DraftJournal(backup);journal.activate('active');const barrier=new ApplicationRestoreDraftBarrier(backup,journal,{assertOwner(){},...options}),snapshot=(revision:number,items=applicationDraftRecoveryItems(saved.retention))=>({version:1 as const,revision,createdAt:'2026-10-08T00:00:00.000Z',autosaves:[],sources:{recovery:{version:1,items}},issues:[]});return{base,current,backup,journal,barrier,retention:saved.retention,snapshot,close:()=>rm(base,{recursive:true,force:true})}}
const code=(expected:string)=>(cause:unknown)=>cause instanceof ApplicationRestoreDraftBarrierError&&cause.code===expected&&!cause.cause
test('AB35-01 application discriminator and both original inert snapshots remain through two exact journal checkpoint ACKs',async()=>{const f=await fixture();try{const before=await readFile(join(f.current,'drafts.json')),first=await f.barrier.inspect();assert.equal(first!.barrier.type,'application');assert.equal(first!.barrier.reason,'APPLICATION_RESTORED');assert.equal(Object.hasOwn(first!.barrier,'workId'),false);const receipt1=await f.journal.persist('active',f.snapshot(2));await f.barrier.checkpoint(f.retention.barrier.token,'active',receipt1);assert.equal((await f.barrier.inspect())!.barrier.phase,'checkpointed');await assert.rejects(f.barrier.acknowledge(f.retention.barrier.token,'active',receipt1),code('APPLICATION_DRAFT_SECOND_CHECKPOINT_REQUIRED'));const receipt2=await f.journal.persist('active',f.snapshot(3));await f.barrier.acknowledge(f.retention.barrier.token,'active',receipt2);const after=await f.barrier.inspect();assert.equal(after!.barrier.phase,'complete');assert.deepEqual(after!.snapshots,f.retention.snapshots);assert.deepEqual(await readFile(join(f.current,'drafts.json')),before);assert.equal((await f.journal.read())!.autosaves.length,0);assert.deepEqual((await f.journal.read())!.sources,{recovery:{version:1,items:applicationDraftRecoveryItems(f.retention)}})}finally{await f.close()}})
test('AB35-02 fabricated receipt, wrong journal owner and missing retained copy cannot unlock application protection',async()=>{const f=await fixture();try{const token=f.retention.barrier.token,path=join(f.backup,'application-restore-drafts.json'),bytes=await readFile(path),receipt=await f.journal.persist('active',f.snapshot(2));await assert.rejects(f.barrier.checkpoint(token,'active',{...receipt,digest:'0'.repeat(64)}),code('APPLICATION_DRAFT_CHECKPOINT_UNCONFIRMED'));await assert.rejects(f.barrier.checkpoint(token,'foreign',receipt),code('APPLICATION_DRAFT_CHECKPOINT_UNCONFIRMED'));assert.deepEqual(await readFile(path),bytes);const missing=await f.journal.persist('active',f.snapshot(3,applicationDraftRecoveryItems(f.retention).slice(1)));await assert.rejects(f.barrier.checkpoint(token,'active',missing),code('APPLICATION_DRAFT_RECOVERY_INCOMPLETE'));assert.deepEqual(await readFile(path),bytes)}finally{await f.close()}})
test('AB35-03 late same-byte journal replacement after ACK remains foreign data and cannot receive a barrier transition',async()=>{let f!:Awaited<ReturnType<typeof fixture>>;f=await fixture({async beforeRename(){const path=join(f.backup,'drafts.json'),bytes=await readFile(path);await rename(path,path+'.preserved');await writeFile(path,bytes)}});try{const path=join(f.backup,'application-restore-drafts.json'),before=await readFile(path),receipt=await f.journal.persist('active',f.snapshot(2));await assert.rejects(f.barrier.checkpoint(f.retention.barrier.token,'active',receipt),code('APPLICATION_DRAFT_CHECKPOINT_CHANGED'));assert.deepEqual(await readFile(path),before);assert.equal((await f.barrier.inspect())!.barrier.phase,'protected');assert.ok((await readFile(join(f.backup,'drafts.json'))).length>0)}finally{await f.close()}})
test('AB35-04 metadata write gate tracks the entire real barrier transition and flush waits a blocked write',async()=>{let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r);let inside=0,completed=0;const f=await fixture({async withWrite<T>(run:()=>Promise<T>){inside++;entered();await gate;try{return await run()}finally{completed++;inside--}},async beforeRename(){assert.equal(inside,1)}});try{const path=join(f.backup,'application-restore-drafts.json'),before=await readFile(path),receipt=await f.journal.persist('active',f.snapshot(2)),pending=f.barrier.checkpoint(f.retention.barrier.token,'active',receipt);await started;let flushed=false;const flush=f.barrier.flush().then(()=>{flushed=true});await new Promise<void>(r=>setImmediate(r));assert.equal(flushed,false);assert.deepEqual(await readFile(path),before);assert.equal(completed,0);release();await pending;await flush;assert.equal(flushed,true);assert.equal(inside,0);assert.equal(completed,1);assert.equal((await f.barrier.inspect())!.barrier.phase,'checkpointed')}finally{release();await f.close()}})
