import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,rm,readFile,writeFile,rename,mkdir,symlink} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {WorkRestoreDraftBarrier} from '../../desktop/main/work-restore-draft-barrier'
const owner=async()=>{}
async function fixture(){const root=await mkdtemp(join(tmpdir(),'xx-restore-barrier-'));return{root,workId:randomUUID(),candidateId:randomUUID(),close:()=>rm(root,{recursive:true,force:true})}}
test('restore barrier remains durable across failure/restart and clears only after matching recovery receipt ACK',async()=>{const f=await fixture();try{let barrier=new WorkRestoreDraftBarrier(f.root);assert.equal(await barrier.inspect(),null);const saved=await barrier.begin({workId:f.workId,candidateId:f.candidateId},owner);assert.equal(saved.outcome.status,'pending');barrier=new WorkRestoreDraftBarrier(f.root);assert.deepEqual(await barrier.inspect(),saved);await assert.rejects(barrier.acknowledge(saved.token,async()=>{throw Error('journal not durable')}),/journal not durable/);assert.deepEqual(await barrier.inspect(),saved);await barrier.settle(saved.token,{status:'failed',message:'旧库未改变'},owner);assert.equal((await barrier.inspect())?.outcome.status,'failed');let confirmed=false;await barrier.acknowledge(saved.token,async()=>{confirmed=true});assert.equal(confirmed,true);assert.equal(await new WorkRestoreDraftBarrier(f.root).inspect(),null)}finally{await f.close()}})
test('a second restore or late token cannot replace/cancel an outstanding draft barrier',async()=>{const f=await fixture();try{const barrier=new WorkRestoreDraftBarrier(f.root),saved=await barrier.begin({workId:f.workId,candidateId:f.candidateId},owner);assert.deepEqual(await barrier.begin({workId:f.workId,candidateId:f.candidateId},owner),saved);await assert.rejects(barrier.begin({workId:f.workId,candidateId:randomUUID()},owner));await assert.rejects(barrier.settle(randomUUID(),{status:'activated'},owner));let verified=false;await assert.rejects(barrier.acknowledge(randomUUID(),async()=>{verified=true}));assert.equal(verified,false);assert.deepEqual(await barrier.inspect(),saved)}finally{await f.close()}})
test('owner loss before durable begin leaves the former journal intact; corrupt and linked barrier state fails closed',async()=>{const f=await fixture();try{let checks=0;const barrier=new WorkRestoreDraftBarrier(f.root);await assert.rejects(barrier.begin({workId:f.workId,candidateId:f.candidateId},async()=>{if(++checks>1)throw Error('owner expired')}));assert.equal(await barrier.inspect(),null);await writeFile(join(f.root,'restore-draft-barrier.json'),'invalid');await assert.rejects(barrier.inspect());await rm(join(f.root,'restore-draft-barrier.json'));await writeFile(join(f.root,'foreign'),'{}');await symlink(join(f.root,'foreign'),join(f.root,'restore-draft-barrier.json'));await assert.rejects(barrier.begin({workId:f.workId,candidateId:f.candidateId},owner));assert.equal(await readFile(join(f.root,'foreign'),'utf8'),'{}')}finally{await f.close()}})
test('uncertain directory sync keeps the actual committed barrier for restart instead of announcing a clean session',async()=>{const f=await fixture();try{const barrier=new WorkRestoreDraftBarrier(f.root,{beforeDirectorySync:async()=>{throw Error('sync denied')}});await assert.rejects(barrier.begin({workId:f.workId,candidateId:f.candidateId},owner));const current=await new WorkRestoreDraftBarrier(f.root).inspect();assert.equal(current?.workId,f.workId);assert.equal(current?.outcome.status,'pending')}finally{await f.close()}})
test('changing the root or recovery receipt while awaiting ACK cannot clear the retained original barrier',async()=>{const f=await fixture(),moved=f.root+'-moved';try{const barrier=new WorkRestoreDraftBarrier(f.root),saved=await barrier.begin({workId:f.workId,candidateId:f.candidateId},owner),before=await readFile(join(f.root,'restore-draft-barrier.json'));await assert.rejects(barrier.acknowledge(saved.token,async()=>{await rename(f.root,moved);await mkdir(f.root)}));assert.deepEqual(await readFile(join(moved,'restore-draft-barrier.json')),before);assert.equal(await new WorkRestoreDraftBarrier(moved).inspect().then(x=>x?.token),saved.token)}finally{await f.close();await rm(moved,{recursive:true,force:true})}})
