import assert from 'node:assert/strict'
import {test} from 'node:test'
import {readFileSync} from 'node:fs'
import {mkdtemp,writeFile,rm,realpath,mkdir} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import ts from 'typescript'
import {transformSync} from 'esbuild'
import {workBackupRequestSchema} from '../../desktop/shared/work-backup'
import {BusinessGate} from '../../desktop/main/business-gate'
import {collectClosedRootFiles} from '../../desktop/main/owned-root-files'
import {directoryIdentity,allowedManagedFile} from '../../desktop/core/root-ownership'
const source=ts.createSourceFile('main.ts',readFileSync('desktop/main/index.ts','utf8'),ts.ScriptTarget.Latest,true)
function declaration(name:string){const node=source.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.ok(node);return node.getText(source)}
function callback(channel:string){let code='';const scan=(node:ts.Node)=>{if(ts.isCallExpression(node)&&node.expression.getText(source)==='businessHandle'&&node.arguments[0].getText(source)===JSON.stringify(channel))code=node.arguments[1].getText(source);ts.forEachChild(node,scan)};scan(source);assert.ok(code);return code}
function create(){const gate=new BusinessGate(),calls:unknown[]=[];let handler:(event:unknown,input:unknown)=>Promise<unknown>=async()=>{};const deps={applicationBlocked:()=>false,applicationRequests:null,businessGate:gate,ipcMain:{handle:(_name:string,fn:typeof handler)=>{handler=fn}},trusted:(event:unknown)=>{if(event!=='trusted')throw Error('untrusted')},workBackupRequestSchema,workBackups:{runNow:async()=>{calls.push('now');return{type:'now',saved:[],failed:[]}}},service:{call:async(method:string,input:unknown)=>{calls.push([method,input]);return{type:'works',works:[]}}}}
 new Function(...Object.keys(deps),transformSync(`${declaration('businessHandle')}\nbusinessHandle('desktop:work-backup',${callback('desktop:work-backup')})`,{loader:'ts'}).code)(...Object.values(deps));return{calls,gate,run:(input:unknown,event:unknown='trusted')=>handler(event,input)}}
test('actual main backup IPC rejects foreign frame, arbitrary path, retention override and activation without approved maintenance',async()=>{const f=create();await assert.rejects(f.run({type:'now'},'foreign'));await assert.rejects(f.run({type:'now',retention:1}));await assert.rejects(f.run({type:'list',workId:randomUUID(),path:'/anything'}));await assert.rejects(f.run({type:'activate',workId:randomUUID(),candidateId:randomUUID(),revision:0}));assert.deepEqual(f.calls,[]);await f.run({type:'now'});assert.deepEqual(f.calls,['now'])})
test('actual main backup IPC cannot bypass close admission and the preload exposes only a semantic channel',async()=>{const f=create();await f.gate.close();await assert.rejects(f.run({type:'works'}),/BUSINESS_CLOSED/);assert.deepEqual(f.calls,[]);f.gate.reopen();await f.run({type:'list',workId:'ef4ab5e0-549c-4738-869b-316eb4af4c6e'});assert.deepEqual(f.calls,[['work-backup',{type:'list',workId:'ef4ab5e0-549c-4738-869b-316eb4af4c6e'}]])
 const preload=ts.createSourceFile('preload.ts',readFileSync('desktop/preload/index.ts','utf8'),ts.ScriptTarget.Latest,true);let bridge='';for(const statement of preload.statements)if(ts.isVariableStatement(statement))for(const entry of statement.declarationList.declarations)if(entry.name.getText(preload)==='bridge')bridge=entry.initializer!.getText(preload);const calls:unknown[]=[];const api=new Function('ipcRenderer',transformSync(`return ${bridge}`,{loader:'ts'}).code)({invoke:(...args:unknown[])=>calls.push(args)});api.workBackup({type:'now'});assert.deepEqual(calls,[['desktop:work-backup',{type:'now'}]])})
test('closed application-root inventory carries durable backup schedule to the new root and preserves unrelated neighboring files',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'xx-backup-owned-')));try{await mkdir(join(root,'inbox'));await writeFile(join(root,'xuanxiang-app.json'),JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:randomUUID(),phase:'ready',inboxReady:true}));await writeFile(join(root,'catalog.json'),JSON.stringify({schemaVersion:1,revision:1,value:[]}));await writeFile(join(root,'backup-plan.json'),JSON.stringify({schemaVersion:1,revision:1,value:{lastSuccess:42}}));await writeFile(join(root,'backup-other.json'),'foreign');const result=await collectClosedRootFiles(await directoryIdentity(root),()=>{});assert.ok(result.files.includes('backup-plan.json'));assert.equal(allowedManagedFile('backup-plan.json'),true);assert.ok(result.preserved.includes('backup-other.json'));assert.equal(allowedManagedFile('backup-other.json'),false)}finally{await rm(root,{recursive:true,force:true})}})
