import assert from 'node:assert/strict'
import {test} from 'node:test'
import {randomUUID} from 'node:crypto'
import {DesktopDraftSession} from '../../src/lib/desktop/draft-session'
import {DesktopSaveCoordinator} from '../../src/lib/desktop/save-coordinator'
import type {DesktopBridge} from '../../desktop/shared/ipc'
import type {DraftSnapshot,DraftReceipt} from '../../desktop/shared/drafts'
function fixture(options:{cleanup?():Promise<void>;persist?(count:number):Promise<void>;confirm?(receipt:DraftReceipt):Promise<void>}={}){
 const trace:string[]=[],coordinator=new DesktopSaveCoordinator({checkpointDelayMs:null}),writes:DraftSnapshot[]=[],replies:unknown[]=[],sessionId=randomUUID()
 const bridge={readDraft:async()=>null,markDraftReady:async()=>{},persistDraft:async(_id:string,snapshot:DraftSnapshot)=>{writes.push(snapshot);trace.push(`write:${writes.length}`);await options.persist?.(writes.length);return{revision:writes.length,digest:'a'.repeat(64),clientRevision:snapshot.revision}},replyClose:async(_id:string,_op:string,reply:unknown)=>{replies.push(reply);return true}} as unknown as DesktopBridge
 const session=new DesktopDraftSession(bridge,coordinator,{restore:()=>options.cleanup?async()=>{trace.push('cleanup');await options.cleanup!()}:undefined,installSources:()=>coordinator.registerSource('recovery',{read:()=>({version:1,items:[]})}),flushSettings:async()=>{},closing:()=>{},restoreBarrier:{confirm:async(receipt:DraftReceipt)=>{trace.push('confirm');await options.confirm?.(receipt)}}})
 return{session,sessionId,trace,writes,replies,close:()=>session.handle({type:'prepare-close',id:randomUUID(),sessionId,action:'flush',retryFailures:false})}
}
test('forced retention checkpoints even an empty startup before acknowledging the durable restore barrier',{timeout:5000},async()=>{const f=fixture();try{await f.session.initialize(f.sessionId);assert.deepEqual(f.trace,['write:1','write:2','confirm'])}finally{f.session.dispose()}})
test('restore barrier ACK follows copied-cache receipt, real cleanup and post-cleanup durable receipt',{timeout:5000},async()=>{const final=Promise.withResolvers<void>(),entered=Promise.withResolvers<void>();const f=fixture({cleanup:async()=>{},persist:async count=>{if(count===2){entered.resolve();await final.promise}},confirm:async receipt=>assert.equal(receipt.revision,2)});const init=f.session.initialize(f.sessionId);try{await entered.promise;assert.deepEqual(f.trace,['write:1','cleanup','write:2']);final.resolve();await init;assert.equal(f.trace.at(-1),'confirm')}finally{final.resolve();await init.catch(()=>{});f.session.dispose()}})
test('failed post-cleanup persistence never clears the durable restore barrier',{timeout:5000},async()=>{const f=fixture({cleanup:async()=>{},persist:async count=>{if(count===2)throw Error('disk full')}});try{await assert.rejects(f.session.initialize(f.sessionId));assert.ok(!f.trace.includes('confirm'))}finally{f.session.dispose()}})
test('a close waits for restore barrier confirmation before acknowledging saved drafts',{timeout:5000},async()=>{const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),f=fixture({confirm:async()=>{entered.resolve();await release.promise}}),init=f.session.initialize(f.sessionId);try{await entered.promise;const close=f.close();await new Promise(setImmediate);assert.equal(f.replies.length,0);release.resolve();await init;await close;assert.equal((f.replies[0] as {status:string}).status,'saved')}finally{release.resolve();await init.catch(()=>{});f.session.dispose()}})

test('disposed initialization cannot clear a recovery barrier after a late checkpoint',{timeout:5000},async()=>{const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),f=fixture({persist:async count=>{if(count===2){entered.resolve();await release.promise}}}),init=f.session.initialize(f.sessionId);try{await entered.promise;f.session.dispose();release.resolve();await assert.rejects(init);assert.ok(!f.trace.includes('confirm'))}finally{release.resolve();await init.catch(()=>{});f.session.dispose()}})
