import assert from 'node:assert/strict'
import {test} from 'node:test'
import {randomUUID} from 'node:crypto'
import {WorkRestoreCommit} from '../../desktop/main/work-restore-commit'
const identity={workId:randomUUID(),candidateId:randomUUID(),revision:2},token=randomUUID()
function fixture(overrides:Record<string,unknown>={}){const calls:string[]=[],options={assertOwner:async()=>{calls.push('owner')},assertClosed:async()=>{calls.push('closed')},barrier:{begin:async()=>{calls.push('barrier');return{token,...identity,createdAt:new Date().toISOString(),outcome:{status:'pending'}}},settle:async(_token:string,result:{status:string})=>{calls.push(`settle:${result.status}`)}},activate:async()=>{calls.push('activate')},closeReopenedData:async()=>{calls.push('close-reopened')},...overrides};return{calls,commit:new WorkRestoreCommit(identity,options as any)}}
test('restoration commit persists the draft barrier before activation and closes reopened data before restart eligibility',async()=>{const f=fixture();assert.equal(f.commit.ready,false);const result=await f.commit.finish();assert.equal(result.status,'activated');assert.equal(f.commit.ready,true);assert.ok(f.calls.indexOf('barrier')<f.calls.indexOf('activate'));assert.ok(f.calls.indexOf('settle:activated')<f.calls.indexOf('close-reopened'));await f.commit.finish();assert.equal(f.calls.filter(x=>x==='activate').length,1)})
test('activation failure is an explicit durable outcome, never successful restoration or a reopened stale renderer',async()=>{let result:any;const f=fixture({activate:async()=>{throw Error('原指针未改变')},barrier:{begin:async()=>({token,outcome:{status:'pending'}}),settle:async(_token:string,value:unknown)=>{result=value}}});assert.deepEqual(await f.commit.finish(),{status:'failed',message:'原指针未改变'});assert.deepEqual(result,{status:'failed',message:'原指针未改变'});assert.equal(f.commit.ready,true);assert.ok(f.calls.includes('close-reopened'))})
test('failed outcome persistence retries the same result without activating twice',async()=>{let attempts=0,activations=0;const f=fixture({activate:async()=>{activations++},barrier:{begin:async()=>({token,outcome:{status:'pending'}}),settle:async()=>{if(++attempts===1)throw Error('disk full')}}});await assert.rejects(f.commit.finish(),/disk full/);assert.equal(f.commit.ready,false);await f.commit.finish();assert.equal(activations,1);assert.equal(f.commit.ready,true)})
test('failed re-close is retryable and cannot make a finished engine operation eligible for early restart',async()=>{let closes=0;const f=fixture({closeReopenedData:async()=>{if(++closes===1)throw Error('engine close failed')}});await assert.rejects(f.commit.finish(),/engine close failed/);assert.equal(f.commit.ready,false);await f.commit.finish();assert.equal(f.calls.filter(x=>x==='activate').length,1);assert.equal(closes,2);assert.equal(f.commit.ready,true)})
test('barrier failure never activates; synchronous observer reentry shares the same finish flight',async()=>{let begin=0,recursive:Promise<unknown>|undefined;const f=fixture({barrier:{begin:async()=>{begin++;recursive=f.commit.finish();if(begin===1)throw Error('sync uncertain');return{token,outcome:{status:'pending'}}},settle:async()=>{}}});const first=f.commit.finish();void first.catch(()=>{});await assert.rejects(first,/sync uncertain/);assert.equal(recursive,first);assert.equal(f.calls.filter(x=>x==='activate').length,0);await f.commit.finish();assert.equal(begin,2);assert.equal(f.calls.filter(x=>x==='activate').length,1)})
