import assert from 'node:assert/strict'
import {test} from 'node:test'
import {readFileSync} from 'node:fs'
import {mkdtemp,rm} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import ts from 'typescript'
import {transformSync} from 'esbuild'
import {WorkRestoreHandoff} from '../../desktop/main/work-restore-handoff'
import {WorkRestoreDraftBarrier} from '../../desktop/main/work-restore-draft-barrier'
import {workRestoreRequestSchema} from '../../desktop/shared/work-restore'
import {CloseCoordinator} from '../../desktop/main/close-coordinator'
import {BusinessGate} from '../../desktop/main/business-gate'
import {ApplicationMetadataGate} from '../../desktop/main/application-metadata-gate'
const source=ts.createSourceFile('main.ts',readFileSync('desktop/main/index.ts','utf8'),ts.ScriptTarget.Latest,true)
function declaration(name:string){const node=source.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.ok(node);return node.getText(source)}
let callback='',services='';const visit=(node:ts.Node)=>{if(ts.isCallExpression(node)&&node.expression.getText(source)==='ipcMain.handle'&&node.arguments[0]?.getText(source)==='"desktop:work-restore"')callback=node.arguments[1].getText(source);if(ts.isNewExpression(node)&&node.expression.getText(source)==='CloseCoordinator')services=node.arguments![0].getText(source);ts.forEachChild(node,visit)};visit(source)
async function fixture(){
 const root=await mkdtemp(join(tmpdir(),'xx-restore-main-flow-')),barrier=new WorkRestoreDraftBarrier(root),gate=new BusinessGate(),calls:string[]=[],action={type:'start' as const,workId:randomUUID(),backupId:randomUUID()},candidate={id:randomUUID(),revision:0,backupId:action.backupId,createdAt:new Date().toISOString()},owner={owner:12,id:randomUUID(),ready:true},window={webContents:{id:12},isDestroyed:()=>false};let declined=false,flushFail=false,settleFail=false,activationFail=false
 const realSettle=barrier.settle.bind(barrier);barrier.settle=async(...args)=>{calls.push('settle');if(settleFail)throw Error('durability');await realSettle(...args)}
 const event={sender:window.webContents},deps={applicationBlocked:()=>false,applicationRequests:null,applicationHandoff:null,ordinaryWorkerExited:false,sessionFlushed:false,applicationMetadata:new ApplicationMetadataGate(),draftJournal:{read:async()=>null},window,draftSession:owner,workBackups:undefined,resumeWorkBackups:async()=>{},restoreDraftBarrier:barrier,workRestoreRequestSchema,WorkRestoreHandoff,CloseCoordinator,businessGate:gate,trusted:(input:unknown)=>{if(input!==event)throw Error('foreign')},migrationHandoff:null,modelService:{activeCount:0,close:async()=>{calls.push('stop-models')},resume:()=>calls.push('resume-models')},modelConfiguration:{activeCount:0,cancelOwner(){}},avatarAssets:{cancelOwner(){}},recoveryExports:{cancelWindow(){},flush:async()=>{}},fileExports:{cancelWindow(){},flush:async()=>{}},configurationFiles:{cancelWindow(){},flush:async()=>{}},repository:{read:async()=>{}},responseOwners:new Map(),conversationDirectories:{revokeAll(){},flush:async()=>{}},closeChannel:{cancel(){}},flushDraftForClose:async()=>{calls.push('flush');if(flushFail)throw Error('draft')},service:{call:async(method:string,input?:{type:string})=>{const key=method==='work-backup'?input!.type:method;calls.push(key);if(key==='task-status')return{active:0};if(key==='prepare')return{type:'prepare',candidate};if(key==='activate'&&activationFail)throw Error('restoration failed');return true}},dialog:{showMessageBox:async(_window:unknown,options:{title:string})=>({response:options.title==='从备份恢复作品'?(declined?0:1):options.title==='恢复交接尚未完成'?1:2})},app:{relaunch:()=>calls.push('relaunch'),quit:()=>calls.push('quit')},worker:{terminate:async()=>{calls.push('terminate')}},send:(e:{type:string})=>calls.push(`event:${e.type}`)}
 const code=`let workLease=null,workRestore=null,businessClosed=false,closingFlow=null,closeCommitted=false,quitting=false;const closePermits=new WeakSet();${declaration('restoreBusiness')}\n${declaration('beginClose')}\nconst closeCoordinator=new CloseCoordinator(${services});const run=${callback};return{run:input=>run(event,input),state:()=>({closed:businessClosed,pending:workRestore?.requiresRestart??false}),replace:()=>{draftSession={...draftSession,id:randomUUID()}}}`
 const all={...deps,event,randomUUID};const api=new Function(...Object.keys(all),transformSync(code,{loader:'ts'}).code)(...Object.values(all)) as {run(input:unknown):Promise<string>;state():{closed:boolean;pending:boolean};replace():void}
 return{...api,calls,gate,barrier,action,decline:()=>{declined=true},failFlush:()=>{flushFail=true},failSettle:(value:boolean)=>{settleFail=value},failActivation:()=>{activationFail=true},cleanup:()=>rm(root,{recursive:true,force:true})}
}
test('actual main confirmation and close services persist the barrier before relaunch and never reopen old business',async()=>{const r=await fixture();try{assert.equal(await r.run(r.action),'restarting');assert.equal((await r.barrier.inspect())?.outcome.status,'activated');assert.equal(r.gate.closed,true);assert.ok(r.calls.indexOf('flush')<r.calls.indexOf('close'));assert.ok(r.calls.indexOf('close')<r.calls.indexOf('activate'));assert.ok(r.calls.indexOf('settle')<r.calls.lastIndexOf('close'));assert.ok(r.calls.lastIndexOf('close')<r.calls.indexOf('relaunch'));assert.ok(r.calls.indexOf('relaunch')<r.calls.indexOf('quit'));assert.equal(r.calls.includes('resume-models'),false)}finally{await r.cleanup()}})
test('actual main cancellation before activation only cancels isolated candidate; source and drafts stay editable',async()=>{for(const boundary of ['confirm','flush']){const r=await fixture();try{if(boundary==='confirm')r.decline();else r.failFlush();assert.equal(await r.run(r.action),'cancelled');assert.equal(await r.barrier.inspect(),null);assert.equal(r.gate.closed,false);assert.ok(r.calls.includes('cancel'));assert.ok(!r.calls.includes('activate'));assert.ok(!r.calls.includes('relaunch'))}finally{await r.cleanup()}}})
test('actual main uncertain settle stays blocked; retry reuses activation outcome and never re-flushes old buffers',async()=>{const r=await fixture();try{r.failSettle(true);assert.equal(await r.run(r.action),'pending');assert.equal(r.state().pending,true);assert.equal(r.gate.closed,true);assert.ok(r.calls.includes('event:work-restore-pending'));assert.equal(r.calls.includes('resume-models'),false);r.failSettle(false);assert.equal(await r.run({type:'retry'}),'restarting');assert.equal(r.calls.filter(x=>x==='flush').length,1);assert.equal(r.calls.filter(x=>x==='activate').length,1);assert.equal(r.calls.filter(x=>x==='relaunch').length,1)}finally{await r.cleanup()}})
test('actual main retains failed activation outcome for the fresh bootstrap rather than claiming success',async()=>{const r=await fixture();try{r.failActivation();assert.equal(await r.run(r.action),'restarting');assert.deepEqual((await r.barrier.inspect())?.outcome,{status:'failed',message:'restoration failed'});assert.ok(r.calls.includes('relaunch'));assert.equal(r.calls.includes('resume-models'),false)}finally{await r.cleanup()}})
