import assert from 'node:assert/strict'
import {test} from 'node:test'
import {build} from 'esbuild'
import {chromium,type Browser,type Page} from 'playwright-core'
const bundle=build({stdin:{loader:'tsx',resolveDir:process.cwd(),contents:`import React from 'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{WorkBackupButton}from'./src/components/desktop/WorkBackupButton';globalThis.mount=()=>{let resolve,reject;const calls=[];window.desktop={workBackup:action=>{calls.push(action);return new Promise((yes,no)=>{resolve=yes;reject=no})}};const root=createRoot(document.getElementById('app'));flushSync(()=>root.render(React.createElement(WorkBackupButton)));return{calls,success:()=>resolve({type:'now',saved:[{id:'one'},{id:'two'}],failed:[]}),failure:()=>reject(Error('作品目录不可读，旧备份已保留')),empty:()=>resolve({type:'now',saved:[],failed:[]}),application:(cleanupPending=0)=>resolve({type:'now',saved:[],failed:[],application:{status:'saved',backup:{cleanupPending}}}),partial:()=>resolve({type:'now',saved:[],failed:[],application:{status:'failed',message:'应用数据备份未完成'}}),workFailure:()=>resolve({type:'now',saved:[],failed:[],application:{status:'saved',backup:{cleanupPending:0}},workError:'作品目录不可读'}),unmount:()=>root.unmount()}}`},bundle:true,platform:'browser',format:'iife',write:false,tsconfig:'tsconfig.json'}).then(r=>r.outputFiles![0].text)
let browser:Browser
test.before(async()=>{browser=await chromium.launch({headless:true,...(process.env.XAANINK_TEST_CHROMIUM?{executablePath:process.env.XAANINK_TEST_CHROMIUM}:{})})});test.after(async()=>{await browser?.close()})
async function scenario(run:(page:Page)=>Promise<void>){const page=await browser.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));try{await page.setContent('<div id="app"></div>');await page.addScriptTag({content:await bundle});await page.evaluate(()=>{(window as any).f=(window as any).mount()});await run(page);assert.deepEqual(errors,[])}finally{await page.close()}}
test('actual backup button waits for persisted completion and blocks duplicate clicks',()=>scenario(async page=>{await page.getByRole('button',{name:'立即备份'}).click();assert.equal(await page.getByRole('button',{name:'正在备份…'}).isDisabled(),true);await page.evaluate(()=>document.querySelector('button')!.click());assert.deepEqual(await page.evaluate(()=>(window as any).f.calls),[{type:'now'}]);await page.evaluate(()=>(window as any).f.success());await page.getByRole('status').filter({hasText:'已完成 2 部作品备份'}).waitFor();assert.equal(await page.getByRole('button',{name:'立即备份'}).isEnabled(),true)}))
test('actual backup button reports failure and allows explicit retry',()=>scenario(async page=>{await page.getByRole('button',{name:'立即备份'}).click();await page.evaluate(()=>(window as any).f.failure());await page.getByRole('alert').filter({hasText:'旧备份已保留'}).waitFor();await page.getByRole('button',{name:'立即备份'}).click();assert.equal(await page.evaluate(()=>(window as any).f.calls.length),2);await page.evaluate(()=>(window as any).f.empty());await page.getByRole('status').filter({hasText:'尚无作品可备份'}).waitFor()}))
test('unmounted backup button ignores a late reply',()=>scenario(async page=>{await page.getByRole('button',{name:'立即备份'}).click();await page.evaluate(()=>{(window as any).f.unmount();(window as any).f.success()});assert.equal(await page.locator('#app').textContent(),'')}))

test('application data is reported backed up even with no registered works and preserves cleanup warnings',()=>scenario(async page=>{await page.getByRole('button',{name:'立即备份'}).click();await page.evaluate(()=>(window as any).f.application(1));await page.getByRole('status').filter({hasText:'已完成应用数据备份'}).waitFor();await page.getByRole('status').filter({hasText:'1 项临时数据待清理'}).waitFor();assert.equal(await page.getByText('尚无作品可备份').count(),0)}))
test('application or work failure cannot be displayed as complete success',()=>scenario(async page=>{await page.getByRole('button',{name:'立即备份'}).click();await page.evaluate(()=>(window as any).f.partial());await page.getByRole('alert').filter({hasText:'应用数据备份未完成'}).waitFor();await page.getByRole('button',{name:'立即备份'}).click();await page.evaluate(()=>(window as any).f.workFailure());await page.getByRole('alert').filter({hasText:'作品目录不可读'}).waitFor();assert.equal(await page.getByRole('status').count(),0)}))
