import assert from 'node:assert/strict'
import {test} from 'node:test'
import {build} from 'esbuild'
import {chromium,type Browser,type Page} from 'playwright-core'
const bundle=build({stdin:{loader:'tsx',resolveDir:process.cwd(),contents:`import React from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{WorkBackupsPanel}from'./src/components/desktop/WorkBackupsPanel';globalThis.mount=()=>{let resolve,reject;const calls=[],lists=[];window.desktop={workBackup:async a=>{calls.push(a);if(a.type==='works')return{type:'works',works:[{id:'work-a',title:'我的长篇'},{id:'work-b',title:'第二部作品'}]};return new Promise(r=>lists.push({work:a.workId,resolve:r}))},restoreWork:a=>{calls.push(a);return new Promise((yes,no)=>{resolve=yes;reject=no})}};const root=createRoot(document.getElementById('app'));flushSync(()=>root.render(React.createElement(WorkBackupsPanel)));return{calls,rows:(work,title)=>lists.find(x=>x.work===work).resolve({type:'list',backups:[{id:'backup-'+work,workId:work,title,createdAt:'2026-10-08T04:00:00Z',bytes:2048,assetCount:0,sha256:'x'}]}),cancel:()=>resolve('cancelled'),fail:()=>reject(Error('备份校验失败，散列不匹配')),unmount:()=>root.unmount()}}`},bundle:true,platform:'browser',format:'iife',write:false,tsconfig:'tsconfig.json'}).then(r=>r.outputFiles![0].text)
let browser:Browser;test.before(async()=>{browser=await chromium.launch({headless:true,...(process.env.XAANINK_TEST_CHROMIUM?{executablePath:process.env.XAANINK_TEST_CHROMIUM}:{})})});test.after(async()=>{await browser?.close()})
async function scenario(run:(page:Page)=>Promise<void>){const page=await browser.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));try{await page.setContent('<div id="app"></div>');await page.addScriptTag({content:await bundle});await page.evaluate(()=>{(window as any).f=(window as any).mount()});await page.getByLabel('备份所属作品').waitFor();await run(page);assert.deepEqual(errors,[])}finally{await page.close()}}
test('actual backup list uses current work, ignores late previous-work response and requests semantic restore once',()=>scenario(async page=>{
 await page.getByLabel('备份所属作品').selectOption('work-b');await page.evaluate(()=>{(window as any).f.rows('work-b','真实作品标题');(window as any).f.rows('work-a','过期列表')});await page.getByText('真实作品标题',{exact:true}).waitFor();assert.equal(await page.getByText('过期列表',{exact:true}).count(),0)
 await page.getByRole('button',{name:'校验并恢复'}).click();assert.equal(await page.getByRole('button',{name:'正在校验备份…'}).isDisabled(),true);assert.equal(await page.getByLabel('备份所属作品').isDisabled(),true);await page.evaluate(()=>document.querySelector('button')!.click());assert.deepEqual(await page.evaluate(()=>(window as any).f.calls.filter((x:any)=>x.type==='start')),[{type:'start',workId:'work-b',backupId:'backup-work-b'}]);await page.evaluate(()=>(window as any).f.cancel());await page.getByRole('status').filter({hasText:'已取消恢复'}).waitFor()
}))
test('actual validation failure preserves the list and offers a deliberate retry',()=>scenario(async page=>{
 await page.evaluate(()=>(window as any).f.rows('work-a','我的长篇备份'));await page.getByRole('button',{name:'校验并恢复'}).click();await page.evaluate(()=>(window as any).f.fail());await page.getByRole('alert').filter({hasText:'散列不匹配'}).waitFor();await page.getByText('我的长篇备份',{exact:true}).waitFor();await page.getByRole('button',{name:'校验并恢复'}).click();assert.equal(await page.evaluate(()=>(window as any).f.calls.filter((x:any)=>x.type==='start').length),2);await page.evaluate(()=>(window as any).f.cancel())
}))
test('unmounted restoration view ignores a late cancelled reply',()=>scenario(async page=>{await page.evaluate(()=>(window as any).f.rows('work-a','备份'));await page.getByRole('button',{name:'校验并恢复'}).click();await page.evaluate(()=>{(window as any).f.unmount();(window as any).f.cancel()});assert.equal(await page.locator('#app').textContent(),'')}))
