import { _electron as electron } from 'playwright'
import { expect } from '@playwright/test'
import { mkdtemp, mkdir, rm, readFile, writeFile } from 'node:fs/promises'
import { createServer } from 'node:http'
import assert from 'node:assert/strict'
import { tmpdir, homedir } from 'node:os'
import { join, resolve } from 'node:path'
const temporary = await mkdtemp(join(tmpdir(), 'xaanink-models-smoke-'))
const evidence = 'docs/evidence/implementation-04'
const startedAt = new Date().toISOString(), checks = [], rendererErrors = []
let app
const requests = []
let release
const server = createServer(async (request,response) => {
  const chunks=[]; for await (const chunk of request) chunks.push(chunk)
  requests.push({path:request.url,authorization:request.headers.authorization,body:JSON.parse(Buffer.concat(chunks).toString())})
  await new Promise(resolve => { release=resolve })
  response.writeHead(200,{'content-type':'application/json'})
  response.end(JSON.stringify({id:'local-fixture',model:'fixture-text',choices:[{index:0,message:{role:'assistant',content:'OK'},finish_reason:'stop'}],usage:{prompt_tokens:4,completion_tokens:1,total_tokens:5}}))
})
await new Promise(resolve => server.listen(0,'127.0.0.1',resolve))
const endpoint=`http://127.0.0.1:${server.address().port}/v1`
await mkdir(evidence, { recursive:true })
try {
  app = await electron.launch({ args:[resolve('.')], env:{...process.env,XAANINK_TEST_ROOT:join(temporary,'data')},timeout:45000 })
  const page = await app.firstWindow({timeout:45000})
  page.on('pageerror', error => rendererErrors.push(error.message))
  await page.getByRole('button',{name:'账号菜单'}).waitFor({timeout:45000})
  await page.getByRole('button',{name:'账号菜单'}).click()
  await page.getByRole('menuitem',{name:'设置',exact:true}).click()
  await page.getByRole('button',{name:'模型',exact:true}).click()
  await page.getByRole('button',{name:'添加文本模型',exact:true}).click({timeout:5000})
  const dialog = page.getByRole('dialog',{name:'配置模型',exact:true})
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button',{name:'保存模型',exact:true})).toBeVisible()
  await expect(dialog.getByRole('button',{name:'测试连接',exact:true})).toBeVisible()
  await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeVisible()
  checks.push('separate text model draft with save/test/cancel actions')
  await page.mouse.click(8,500)
  await expect(page.locator('.desktop-settings')).not.toBeVisible()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button',{name:'账号菜单'}).click()
  await page.getByRole('menuitem',{name:'设置',exact:true}).click()
  await page.getByRole('button',{name:'模型',exact:true}).click()
  await page.getByRole('button',{name:'添加文本模型',exact:true}).click()
  checks.push('outside click dismisses settings and model draft without click-through')
  await dialog.getByLabel('供应商',{exact:true}).click()
  await expect(page.getByRole('option')).toHaveCount(13)
  await expect(page.getByRole('option').filter({hasText:'智谱'}).locator('img')).toHaveAttribute('src','/brands/providers/zai.svg')
  await page.getByLabel('搜索供应商',{exact:true}).fill('自定义')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Space')
  await expect(page.locator('.desktop-choice-popup')).not.toBeVisible()
  await expect(dialog.getByLabel('供应商',{exact:true})).toContainText('自定义供应商')
  checks.push('provider search and ArrowDown/Space commit a single option')
  await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].setSize(800,600))
  await expect(dialog.getByRole('button',{name:'保存模型',exact:true})).toBeInViewport()
  await expect(dialog.getByRole('button',{name:'测试连接',exact:true})).toBeInViewport()
  await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeInViewport()
  assert.equal(await dialog.locator('fieldset').evaluate(element => element.scrollHeight > element.clientHeight),true)
  checks.push('short native window keeps all three actions visible while only model fields scroll')
  await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].setSize(1440,940))
  await dialog.getByRole('textbox',{name:'供应商名称',exact:true}).fill('本机验收夹具')
  await dialog.getByRole('combobox',{name:'协议',exact:true}).selectOption('openai')
  await dialog.getByRole('textbox',{name:'展示名称',exact:true}).fill('本机文本模型')
  await dialog.getByRole('textbox',{name:'Base URL',exact:true}).fill(endpoint)
  await dialog.getByRole('textbox',{name:'模型 ID',exact:true}).fill('fixture-text')
  await dialog.getByLabel('API Key',{exact:true}).fill('public-local-fixture-key')
  await dialog.getByRole('button',{name:'测试连接',exact:true}).click()
  await expect.poll(() => requests.length).toBe(1)
  assert.equal(requests[0].authorization,'Bearer public-local-fixture-key')
  assert.equal(requests[0].body.model,'fixture-text')
  assert.equal(requests[0].path,'/v1/chat/completions')
  await expect(dialog.getByRole('button',{name:'测试中…',exact:true})).toBeDisabled()
  await expect(dialog.getByRole('button',{name:'保存模型',exact:true})).toBeDisabled()
  await expect(dialog.getByLabel('API Key',{exact:true})).toBeDisabled()
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).models.length,0)
  release()
  const result=page.getByRole('dialog',{name:'连接测试结果',exact:true})
  await expect(result).toContainText('当前模型连接成功')
  await result.getByRole('button',{name:'返回配置',exact:true}).click()
  await expect(dialog.getByRole('button',{name:'测试连接',exact:true})).toBeFocused()
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).models.length,0)
  await dialog.getByRole('button',{name:'保存模型',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  const state=await page.evaluate(() => window.desktop.bootstrap())
  assert.equal(state.models.length,1)
  assert.equal(state.models[0].contextWindow,0)
  assert.equal(JSON.stringify(state).includes('public-local-fixture-key'),false)
  assert.equal((await readFile(join(temporary,'data','state.json'),'utf8')).includes('public-local-fixture-key'),false)
  checks.push('native main-only loopback text test freezes draft, shows result and never saves automatically','saved key is encrypted by real macOS safeStorage and absent from public state','unknown context capacity remains unknown')
  await page.getByRole('button',{name:'编辑模型 本机文本模型',exact:true}).click()
  await expect(dialog.getByLabel('API Key',{exact:true})).toHaveValue('')
  await dialog.getByRole('textbox',{name:'展示名称',exact:true}).fill('取消的改名')
  await dialog.getByRole('button',{name:'取消',exact:true}).click()
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).models[0].name,'本机文本模型')
  await page.getByRole('button',{name:'编辑模型 本机文本模型',exact:true}).click()
  await dialog.getByRole('textbox',{name:'展示名称',exact:true}).fill('已保存的模型')
  await dialog.getByRole('button',{name:'保存模型',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).models[0].authRevision,1)
  await page.getByRole('button',{name:'编辑模型 已保存的模型',exact:true}).click()
  await dialog.getByRole('button',{name:'测试连接',exact:true}).click()
  await expect.poll(() => requests.length).toBe(2)
  await dialog.getByRole('button',{name:'取消',exact:true}).click()
  release()
  await expect(dialog).not.toBeVisible()
  await expect(result).not.toBeVisible()
  await expect(page.getByRole('button',{name:'编辑模型 已保存的模型',exact:true})).toBeFocused()
  checks.push('test result returns focus to test action; cancelling active test ignores late reply and restores edit focus')
  await page.getByRole('button',{name:'添加文生图模型',exact:true}).click()
  await dialog.getByLabel('供应商',{exact:true}).click()
  await expect(page.getByRole('option')).toHaveCount(9)
  await expect(page.getByRole('option').filter({hasText:'Anthropic'})).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('供应商',{exact:true})).toBeFocused()
  await expect(page.locator('.desktop-choice-popup')).not.toBeVisible()
  await dialog.getByRole('button',{name:'取消',exact:true}).click()
  checks.push('cancelled model edits never persist; blank-key metadata save retains authorization','provider menus filter 12 text and 8 image presets plus custom')
  await page.getByRole('button',{name:'智能体',exact:true}).click()
  await page.getByLabel('默认模型',{exact:true}).click()
  await page.getByRole('option').filter({hasText:'已保存的模型'}).click()
  await expect.poll(async () => (await page.evaluate(() => window.desktop.bootstrap())).settings.agent.textModelId).toBe(state.models[0].id)
  await page.getByRole('button',{name:'模型',exact:true}).click()
  await page.getByRole('button',{name:'停用模型 已保存的模型',exact:true}).click()
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).models[0].enabled,true)
  await page.getByRole('dialog',{name:'停用模型',exact:true}).getByRole('button',{name:'取消',exact:true}).click()
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).models[0].enabled,true)
  await page.getByRole('button',{name:'停用模型 已保存的模型',exact:true}).click()
  await page.getByRole('dialog',{name:'停用模型',exact:true}).getByRole('button',{name:'停用模型',exact:true}).click()
  await expect.poll(async () => (await page.evaluate(() => window.desktop.bootstrap())).models[0].enabled).toBe(false)
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).settings.agent.textModelId,state.models[0].id)
  await page.getByRole('button',{name:'删除模型 已保存的模型',exact:true}).click()
  await page.getByRole('dialog',{name:'删除模型',exact:true}).getByRole('button',{name:'删除模型',exact:true}).click()
  await expect.poll(async () => (await page.evaluate(() => window.desktop.bootstrap())).models.length).toBe(0)
  assert.equal((await page.evaluate(() => window.desktop.bootstrap())).settings.agent.textModelId,null)
  checks.push('agent selection persists; disable retains invalid reference; deletion clears reference without replacement')
  assert.deepEqual(rendererErrors,[])
  await writeFile(join(evidence,'models-latest.json'),JSON.stringify({scope:'development Electron model configuration only; not formal acceptance',startedAt,completedAt:new Date().toISOString(),status:'passed',checks},null,2)+'\n')
} catch(error) {
  const message=String(error).replaceAll(process.cwd(),'<repo>').replaceAll(temporary,'<isolated-temp>').replaceAll(homedir(),'<home>')
  await writeFile(join(evidence,'models-latest.json'),JSON.stringify({scope:'development Electron model configuration only',startedAt,status:'failed',checks,error:message},null,2)+'\n')
  throw error
} finally { release?.(); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); await app?.close().catch(()=>{}); await rm(temporary,{recursive:true,force:true}) }
