// Checks the HTML design viewer only. This never launches the application or calls providers.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from '@playwright/test';

const directory = path.dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, ignoreDefaultArgs: ['--hide-scrollbars'] });
const page = await browser.newPage({ viewport: { width: 1380, height: 1040 }, deviceScaleFactor: 1 });
const pageErrors = [], failedRequests = [], externalRequests = [], checks = [], captures = [];
page.on('pageerror', error => pageErrors.push(String(error)));
page.on('requestfailed', request => failedRequests.push({ url: request.url().replace(/^.*\/design\//, 'design/'), error: request.failure()?.errorText }));
page.on('request', request => { if (/^https?:/.test(request.url())) externalRequests.push(request.url()); });
let frame;
function check(name, details = {}) { checks.push({ name, passed: true, ...details }); }
async function title(expected) { await frame.getByRole('heading', { name: expected, exact: true }).waitFor(); }
async function selectStep(value) { await page.locator('#jump').selectOption(value); await title({ theme: '先选一个喜欢的界面', profile: '填写用户信息', text: '配置文本模型', 'image-choice': '要配置文生图模型吗？', image: '配置文生图模型', done: '引导完成' }[value]); }
async function screenshot(name) {
  await frame.evaluate(() => document.fonts.ready);
  await page.evaluate(() => document.fonts.ready);
  const geometry = await frame.locator('#onboarding').evaluate(el => {
    const rect = el.getBoundingClientRect(), footer = el.querySelector('.dialog-footer').getBoundingClientRect(), title = el.querySelector('h1').getBoundingClientRect(), body = el.querySelector('.dialog-body');
    return { width: rect.width, height: rect.height, left: rect.left, top: rect.top, right: rect.right, bottom: rect.bottom, viewport: { width: innerWidth, height: innerHeight }, footerBottom: footer.bottom, titleTop: title.top, bodyScrollHeight: body.scrollHeight, bodyHeight: body.clientHeight, horizontalOverflow: el.scrollWidth > el.clientWidth + 1, look: document.documentElement.className };
  });
  assert(geometry.left >= 0 && geometry.top >= 0 && geometry.right <= geometry.viewport.width + 1 && geometry.bottom <= geometry.viewport.height + 1, `${name}: dialog contained`);
  assert(geometry.footerBottom <= geometry.bottom + 1 && geometry.titleTop >= geometry.top, `${name}: fixed title and footer visible`);
  assert.equal(geometry.horizontalOverflow, false, `${name}: no dialog horizontal overflow`);
  await page.screenshot({ path: path.join(directory, `${name}.png`), fullPage: true });
  if (['preview-theme-paper', 'preview-theme-ink'].includes(name)) await frame.locator('#onboarding').screenshot({ path: path.join(directory, `${name}-dialog.png`) });
  captures.push({ name, geometry });
}
try {
  await page.goto(pathToFileURL(path.join(directory, 'index.html')).href);
  await page.frameLocator('#preview').getByRole('heading', { name: '先选一个喜欢的界面' }).waitFor();
  frame = page.frames().find(item => item.url().endsWith('/flow.html'));
  assert(frame); await screenshot('preview-theme-paper');
  await frame.getByRole('radio', { name: '玄墨', exact: true }).check();
  await frame.getByText('主题已应用。可以继续填写用户信息。').waitFor();
  assert.equal(await frame.locator('html').getAttribute('class'), 'ink');
  await screenshot('preview-theme-ink');
  await frame.getByRole('radio', { name: '宣纸', exact: true }).check(); await frame.getByRole('button', { name: '继续', exact: true }).waitFor({ state: 'visible' });
  await frame.waitForFunction(() => !document.querySelector('[data-action="confirm-theme"]').disabled);
  await frame.getByRole('radio', { name: '宣纸', exact: true }).focus(); await page.keyboard.press('ArrowRight');
  await frame.waitForFunction(() => document.querySelector('[value="ink"][name="theme"]').checked && !document.querySelector('[data-action="confirm-theme"]').disabled);
  assert.equal(await frame.locator('html').getAttribute('class'), 'ink');
  check('Theme radio arrow key and immediate appearance');
  await frame.getByRole('radio', { name: '宣纸', exact: true }).check(); await frame.waitForFunction(() => !document.querySelector('[data-action="confirm-theme"]').disabled);
  await frame.getByRole('button', { name: '继续', exact: true }).click(); await title('填写用户信息'); await screenshot('preview-profile');
  await frame.getByRole('textbox', { name: '笔名', exact: true }).fill(''); await frame.getByRole('button', { name: '确定', exact: true }).click();
  assert.equal(await frame.getByRole('textbox', { name: '笔名', exact: true }).getAttribute('aria-invalid'), 'true');
  await frame.getByRole('textbox', { name: '笔名', exact: true }).fill('作者'); await frame.getByRole('button', { name: '确定', exact: true }).click(); await title('配置文本模型');
  check('Profile required name, optional email and confirm transition');
  await frame.getByRole('button', { name: '确定', exact: true }).click(); assert(await frame.getByRole('alert').textContent());
  await frame.getByLabel('API Key', { exact: true }).fill('preview-placeholder'); await frame.getByLabel('可用模型', { exact: true }).selectOption('design-text');
  await page.locator('#scenario').selectOption('save-failure');
  await frame.getByRole('button', { name: '确定', exact: true }).click(); await frame.getByText('配置暂未保存，请检查目录权限后重试。已确认的内容保留。').waitFor();
  assert.equal(await frame.getByLabel('可用模型', { exact: true }).inputValue(), 'design-text');
  await screenshot('preview-text-save-failure');
  check('Model draft kept on simulated save failure');
  await frame.getByRole('button', { name: '确定', exact: true }).click(); await title('要配置文生图模型吗？'); await screenshot('preview-image-choice');
  await frame.getByRole('button', { name: '返回', exact: true }).click(); await title('配置文本模型');
  await frame.getByLabel('供应商', { exact: true }).selectOption('deepseek'); await frame.getByLabel('可用模型', { exact: true }).selectOption('design-text');
  await frame.getByRole('button', { name: '确定', exact: true }).click(); assert.match(await frame.getByRole('alert').textContent(), /请输入 API Key/);
  check('Changing provider after prior confirmation requires a fresh Key');
  await frame.getByLabel('API Key', { exact: true }).fill('preview-placeholder'); await frame.getByRole('button', { name: '确定', exact: true }).click(); await title('要配置文生图模型吗？');
  await frame.getByRole('button', { name: '跳过', exact: true }).click(); await title('引导完成');
  assert.match(await frame.locator('dl').textContent(), /默认文本模型.*文本模型（设计占位）.*默认审核模型.*文本模型（设计占位）.*默认文生图模型.*暂未配置/s);
  await screenshot('preview-done-skip'); check('Full path order and skip at image question');
  await frame.getByRole('button', { name: '进入工作台', exact: true }).click(); await frame.getByRole('heading', { name: '准备开始创作', exact: true }).waitFor();
  await page.getByRole('button', { name: '重置预览', exact: true }).click(); await title('先选一个喜欢的界面');
  await selectStep('image-choice'); await frame.getByRole('button', { name: '配置文生图模型', exact: true }).click(); await title('配置文生图模型');
  await screenshot('preview-image');
  await frame.getByLabel('API Key', { exact: true }).fill('preview-placeholder'); await frame.getByLabel('可用模型', { exact: true }).selectOption('design-image');
  await frame.getByRole('button', { name: '跳过', exact: true }).click(); await title('引导完成'); assert.match(await frame.locator('dl').textContent(), /默认文生图模型.*暂未配置/s);
  check('Skip from image editor discards unsaved configuration');
  await selectStep('image'); await frame.getByLabel('API Key', { exact: true }).fill('preview-placeholder'); await frame.getByLabel('可用模型', { exact: true }).selectOption('design-image');
  await frame.getByRole('button', { name: '确定', exact: true }).click(); await title('引导完成'); assert.match(await frame.locator('dl').textContent(), /默认文生图模型.*文生图模型（设计占位）/s);
  check('Image confirmation produces preview default summary');
  await page.getByRole('button', { name: '无文本模型入口', exact: true }).click(); await title('尚未配置文本模型'); await screenshot('preview-model-entry');
  await frame.getByRole('button', { name: '开始配置', exact: true }).click(); await title('配置文本模型');
  assert.equal(await frame.locator('.progress li').count(), 3);
  assert.equal(await page.locator('#flow-list li:visible').count(), 3);
  assert.equal(await page.locator('#flow-list li:visible').first().locator('span').textContent(), '1');
  await page.locator('#scenario').selectOption('existing');
  await frame.getByLabel('已配置模型', { exact: true }).selectOption('existing-text');
  await frame.getByRole('button', { name: '确定', exact: true }).click(); await title('要配置文生图模型吗？');
  await frame.getByRole('button', { name: '跳过', exact: true }).click(); await title('引导完成');
  assert.equal(await frame.locator('dl dt').count(), 3);
  check('Short flow excludes theme/profile and can select an existing model');
  await page.getByRole('button', { name: '首次完整引导', exact: true }).click(); await title('先选一个喜欢的界面'); await selectStep('text');
  await frame.getByLabel('API Key', { exact: true }).fill('preview-placeholder'); await page.keyboard.press('Escape');
  await frame.getByRole('heading', { name: '已暂时退出引导', exact: true }).waitFor();
  assert.equal(await frame.locator('#api-key').count(), 0);
  await frame.getByRole('button', { name: '继续新手引导', exact: true }).click(); await title('配置文本模型'); assert.equal(await frame.getByLabel('API Key', { exact: true }).inputValue(), '');
  check('Escape exits and resume clears unsubmitted Key');
  await page.locator('#scenario').selectOption('catalog-failure'); assert.match(await frame.getByRole('status').textContent(), /目录读取失败/);
  await frame.getByLabel('可用模型', { exact: true }).selectOption('design-text'); check('Catalog failure keeps design candidates selectable');
  await page.locator('#scenario').selectOption('normal'); await page.getByRole('button', { name: '短窗', exact: true }).click();
  await frame.getByLabel('供应商', { exact: true }).selectOption('custom');
  await screenshot('preview-short-custom');
  const scroll = await frame.locator('.dialog-body').evaluate(el => ({ height: el.clientHeight, scroll: el.scrollHeight })); assert(scroll.scroll > scroll.height);
  await frame.getByRole('button', { name: '确定', exact: true }).focus(); await page.keyboard.press('Tab');
  assert.equal(await frame.evaluate(() => document.activeElement.dataset.action), 'exit');
  check('Short custom form scrolls, footer stays visible and Tab wraps in native dialog');
  await page.getByRole('button', { name: '常规', exact: true }).click(); await selectStep('theme');
  await frame.getByRole('radio', { name: '玄墨', exact: true }).check(); await page.locator('#jump').selectOption('profile'); await title('填写用户信息');
  await frame.waitForTimeout(350); assert.equal(await frame.getByRole('heading', { name: '填写用户信息', exact: true }).count(), 1);
  check('Review jump during theme save cancels late page callbacks');
  await selectStep('theme'); await frame.getByRole('radio', { name: '跟随系统', exact: true }).check(); await frame.waitForFunction(() => !document.querySelector('[data-action="confirm-theme"]').disabled);
  await page.emulateMedia({ colorScheme: 'dark' }); await frame.waitForFunction(() => document.documentElement.className === 'ink');
  await page.emulateMedia({ colorScheme: 'light' }); await frame.waitForFunction(() => document.documentElement.className === 'paper');
  assert.equal(await frame.getByRole('radio', { name: '跟随系统', exact: true }).isChecked(), true);
  check('System theme follows media changes while retaining system selection');
  await page.getByRole('button', { name: '常规', exact: true }).click(); await selectStep('theme');
  await page.setViewportSize({ width: 360, height: 1000 }); await screenshot('preview-mobile-theme');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false);
  check('360px viewer has no horizontal overflow');
  assert.deepEqual(pageErrors, []); assert.deepEqual(failedRequests, []); assert.deepEqual(externalRequests, []);
  check('No script errors, failed assets or HTTP requests');
  await fs.writeFile(path.join(directory, 'preview-checks.json'), JSON.stringify({ date: '2026-10-11', scope: 'HTML design viewer only, not product tests', command: 'node design/onboarding/capture-preview.mjs', status: 'passed', checks, captures, pageErrors, failedRequests, externalRequests }, null, 2) + '\n');
  console.log(JSON.stringify({ scope: 'HTML design viewer only', checks: checks.length, captures: captures.length, errors: pageErrors.length, externalRequests: externalRequests.length }));
} finally { await browser.close(); }
