"use client"
import { useState, useRef } from "react"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { Plus, Trash2, FileText } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Switch } from "@/components/ui/switch"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { apiFetch, EmptyState, TableSkeleton } from "@/components/admin/shared"
import { cn } from "@/lib/utils"
import type { WizardCategory, WizardTemplate } from "@/lib/creation-wizard/taxonomy"
import type { LocalWizardItem } from "@desktop/shared/template-library"

const categoryNames:Record<WizardCategory,string>={theme:"主题",world:"世界观",character:"角色",plot:"剧情"}
const blank=():LocalWizardItem=>({template:{id:"",cat:"theme",title:"",summary:"",channels:[],genres:[],tags:[],prompt:""},version:1,enabled:true,source:"user"})
export function WizardTemplatesClient(){
 const queryClient=useQueryClient(),[selectedId,setSelectedId]=useState<string|null>(null),[draft,setDraft]=useState<LocalWizardItem|null>(null),[create,setCreate]=useState(false),[deleting,setDeleting]=useState(false),[error,setError]=useState<string|null>(null)
 const live=useRef({draft,selectedId,create});live.current={draft,selectedId,create}
 const [fieldText,setFieldText]=useState<Record<string,string>>({})
 const query=useQuery({queryKey:["desktop","wizard-templates"],queryFn:()=>apiFetch<{templates:LocalWizardItem[]}>("/api/templates/wizard")})
 const selected=query.data?.templates.find(p=>p.template.id===selectedId),current=draft??selected
 const refresh=()=>queryClient.invalidateQueries({queryKey:["desktop","wizard-templates"]})
 const save=useMutation({mutationFn:({item,creating}:{item:LocalWizardItem;creating:boolean})=>apiFetch<{template:LocalWizardItem}>(creating?"/api/templates/wizard":`/api/templates/wizard/${item.template.id}`,{method:creating?"POST":"PATCH",body:JSON.stringify({template:item.template,enabled:item.enabled,...(!creating?{expectedVersion:item.version}:{})})}),onSuccess:(result,{item,creating})=>{void refresh();if(live.current.draft?.template.id===item.template.id)setError(null);if(creating&&live.current.draft?.template.id===item.template.id){setSelectedId(result.template.template.id);setCreate(false)}else if(!creating)setSelectedId(previous=>previous===item.template.id?result.template.template.id:previous);setDraft(previous=>previous===item?null:previous?.template.id===item.template.id&&previous.version===item.version?{...previous,version:result.template.version}:previous)},onError:error=>setError(error.message)})
 const remove=useMutation({mutationFn:(item:LocalWizardItem)=>apiFetch(`/api/templates/wizard/${item.template.id}`,{method:"DELETE",body:JSON.stringify({expectedVersion:item.version})}),onSuccess:(_result,item)=>{void refresh();setSelectedId(previous=>previous===item.template.id?null:previous);setDraft(previous=>previous?.template.id===item.template.id?null:previous);setDeleting(false);setError(null)},onError:error=>setError(error.message)})
 const set=(patch:Partial<WizardTemplate>)=>current&&setDraft({...current,template:{...current.template,...patch}})
 const dirty=create||!!draft&&JSON.stringify(draft)!==JSON.stringify(selected)
 const listField=(field:"channels"|"genres"|"tags"|"lengths",label:string)=><div className="grid gap-2"><Label>{label}</Label><Input aria-label={label} value={fieldText[`${current?.template.id}:${field}`]??current?.template[field]?.join("，")??""} onChange={e=>{setFieldText(previous=>({...previous,[`${current?.template.id}:${field}`]:e.target.value}));set({[field]:e.target.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean)})}}/></div>
 return <div className="space-y-3">{error||query.error?<p role="alert" className="text-sm text-destructive">{error??query.error?.message}</p>:null}<div className="flex flex-col gap-6 sm:flex-row">
  <div className="w-full shrink-0 rounded-lg border sm:w-64"><div className="flex items-center justify-between border-b px-3 py-2"><span className="text-sm font-medium">创作模板列表</span><Button variant="ghost" size="sm" onClick={()=>{setFieldText({});setCreate(true);setDraft(blank());setSelectedId(null);setError(null)}}><Plus className="size-4"/>新建</Button></div><ScrollArea className="h-[calc(100svh-19rem)]">{query.isLoading?<TableSkeleton columns={1} rows={8}/>:!query.data?.templates.length?<EmptyState text="暂无创作模板"/>:query.data.templates.map(row=><button key={row.template.id} type="button" onClick={()=>{setFieldText({});setSelectedId(row.template.id);setDraft(null);setCreate(false);setError(null)}} className={cn("flex w-full flex-col gap-1 rounded-lg px-3 py-2 text-left text-sm hover:bg-muted",row.template.id===selectedId&&"bg-primary/10 text-primary")}><span className="flex items-center gap-2"><FileText className="size-3.5"/>{row.template.title}{!row.enabled?<Badge variant="outline">停用</Badge>:null}</span><span className="font-mono text-xs text-muted-foreground">{categoryNames[row.template.cat]} · {row.template.id} · v{row.version}</span></button>)}</ScrollArea></div>
  <div className="min-w-0 flex-1">{!current?<div className="flex h-64 items-center justify-center rounded-lg border border-dashed text-sm text-muted-foreground">从左侧选择一个模板，或点击「新建」</div>:<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2"><Badge variant="secondary">v{current.version}</Badge><Badge variant="outline">{current.source==="builtin"?"内置模板":current.source==="customized"?"已自定义":"用户模板"}</Badge></div><div className="flex gap-2">{!create?<Button variant="outline" size="sm" onClick={()=>{setFieldText({});setDraft({...current,template:{...current.template,id:`${current.template.id}.copy`,title:`${current.template.title}（副本）`},version:1,source:"user"});setCreate(true)}}>另存为</Button>:null}<Button variant="ghost" size="sm" disabled={create||current.source!=="user"||remove.isPending} onClick={()=>setDeleting(true)}><Trash2 className="size-4"/>删除</Button><Button size="sm" disabled={!dirty||save.isPending||!current.template.id||!current.template.title||!current.template.prompt} onClick={()=>save.mutate({item:current,creating:create})}>保存</Button></div></div>
  <div className="grid gap-2"><Label>唯一标识</Label><Input aria-label="创作模板标识" value={current.template.id} disabled={!create} onChange={e=>set({id:e.target.value})}/></div><div className="grid gap-2"><Label>名称</Label><Input aria-label="创作模板名称" value={current.template.title} onChange={e=>set({title:e.target.value})}/></div>
  <div className="grid gap-2"><Label>环节</Label><Select value={current.template.cat} onValueChange={value=>value&&set({cat:value as WizardCategory})}><SelectTrigger aria-label="创作模板环节"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(categoryNames).map(([key,name])=><SelectItem key={key} value={key}>{name}</SelectItem>)}</SelectContent></Select></div>
  <div className="grid gap-2"><Label>摘要</Label><Textarea aria-label="创作模板摘要" value={current.template.summary} onChange={e=>set({summary:e.target.value})}/></div>
  {listField("channels","频道（逗号分隔）")}{listField("genres","题材（逗号分隔）")}{listField("tags","标签（逗号分隔）")}{listField("lengths","篇幅（逗号分隔）")}
  <div className="grid gap-2"><Label>主角类型</Label><Input aria-label="主角类型" value={current.template.archetype??""} onChange={e=>set({archetype:e.target.value})}/></div><div className="grid gap-2"><Label>拼贴内容</Label><Textarea aria-label="创作模板拼贴内容" rows={10} value={current.template.prompt} onChange={e=>set({prompt:e.target.value})}/></div><div className="flex items-center justify-between rounded-lg border p-3"><Label>启用该模板</Label><Switch checked={current.enabled} onCheckedChange={enabled=>setDraft({...current,enabled})}/></div>
  </div>}</div></div><Dialog open={deleting} onOpenChange={setDeleting}><DialogContent><DialogHeader><DialogTitle>删除创作模板</DialogTitle><DialogDescription>删除用户副本「{current?.template.title}」，内置模板保留。</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setDeleting(false)}>取消</Button><Button variant="destructive" disabled={remove.isPending} onClick={()=>current&&remove.mutate(current)}>确认删除</Button></DialogFooter></DialogContent></Dialog></div>
}
