import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,mkdir,writeFile,readFile,readdir,realpath,rm} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {directoryIdentity} from '../../desktop/core/root-ownership'
import {assertNoLegacyBackupRecovery} from '../../desktop/main/legacy-recovery-preflight'

async function fixture(){
 const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-removal-review110-'))),boot=join(base,'bootstrap'),root=join(base,'data')
 await mkdir(boot);await mkdir(root)
 const pointer={schemaVersion:1,revision:1,rootId:randomUUID(),migrationId:null,root:await directoryIdentity(root)}
 await writeFile(join(boot,'data-root.json'),JSON.stringify(pointer)+'\n')
 return{base,boot,root}
}

test('BR110-R01 actual former request temporary namespace blocks startup read-only before an ordinary engine/session',async()=>{
 const f=await fixture()
 try{
  // This is the exact temporary prefix generated by the original request publisher.
  const name='.application-recovery-'+randomUUID()+'.tmp',path=join(f.boot,name),bytes='interrupted original immutable phase/request bytes'
  await writeFile(path,bytes)
  const pointer=await readFile(join(f.boot,'data-root.json')),entries=await readdir(f.boot)
  assert.throws(()=>assertNoLegacyBackupRecovery(f.boot,()=>{}),/LEGACY_BACKUP_RECOVERY/,'an unpublished original request/phase temp cannot be ignored as ordinary startup')
  assert.equal(await readFile(path,'utf8'),bytes)
  assert.deepEqual(await readFile(join(f.boot,'data-root.json')),pointer)
  assert.deepEqual(await readdir(f.boot),entries)
 }finally{await rm(f.base,{recursive:true,force:true})}
})

test('BR110-R02 unknown old application-recovery controls cannot bypass the strict request reader',async()=>{
 const f=await fixture()
 try{
  const path=join(f.boot,'application-recovery-unknown.json'),bytes='{"unrecognized":"legacy control"}'
  await writeFile(path,bytes)
  assert.throws(()=>assertNoLegacyBackupRecovery(f.boot,()=>{}),/LEGACY_BACKUP_RECOVERY/)
  assert.equal(await readFile(path,'utf8'),bytes)
 }finally{await rm(f.base,{recursive:true,force:true})}
})

test('BR110-R03 exact former activation pointer/receipt temporary namespace blocks ordinary startup without touching its unpublished bytes',async()=>{
 const f=await fixture()
 try{
  // Original ApplicationRestoreActivation.temporary creates this namespace
  // before publishing either the receipt or pointer; a crash can retain it.
  const path=join(f.boot,'.application-restore-'+randomUUID()+'.tmp'),bytes='unpublished original pointer or activation receipt'
  await writeFile(path,bytes)
  const pointer=await readFile(join(f.boot,'data-root.json'))
  assert.throws(()=>assertNoLegacyBackupRecovery(f.boot,()=>{}),/LEGACY_BACKUP_RECOVERY/)
  assert.equal(await readFile(path,'utf8'),bytes)
  assert.deepEqual(await readFile(join(f.boot,'data-root.json')),pointer)
 }finally{await rm(f.base,{recursive:true,force:true})}
})
