import assert from "node:assert/strict"
import { test } from "node:test"
import { useChatStore } from "../../src/stores/chat"
import { registerStagedInterception, useStagedChangesStore, type StagedBatch } from "../../src/stores/staged-changes"
import { apiSend } from "../../src/components/content/api"
import { AutosaveController } from "../../src/lib/autosave-controller"
import { useSceneUiStore } from "../../src/stores/scene-ui"
import { ChatSessionRepository, chatSessionKey, emptyChatSession } from "../../src/lib/chat-session"
import { DesktopSaveCoordinator } from "../../src/lib/desktop/save-coordinator"
import { installDesktopDraftSources } from "../../src/lib/desktop/draft-sources"
function fixture(){const chat=useChatStore.getState(),staged=useStagedChangesStore.getState(),scene=useSceneUiStore.getState(),map=new Map<string,string>(),reads:string[]=[];const storage={getItem(key:string){reads.push(key);return map.get(key)??null},setItem(key:string,value:string){map.set(key,value)},removeItem(key:string){map.delete(key)}};const coordinator=new DesktopSaveCoordinator({checkpointDelayMs:null});useChatStore.setState({accountId:"source-test-owner",conversationId:null,draftId:"active-draft",draft:"当前未发送输入",draftNovelId:"local-novel",pendingNovelTitle:"待创建作品",pendingNovelPosition:null,novelCreationRequestId:"stable-create",pendingRequest:null,draftAction:null,queuedMessages:[],modelChoice:{modelId:null,effort:null},modelChoiceExplicit:true,mode:"plan",modeExplicit:true,isGenerating:false,creatingNovel:false,suspendedExecution:false,pendingQuestion:null});useStagedChangesStore.setState({batches:{},chips:[]});useSceneUiStore.setState({drafts:{},imageDrafts:{},imageRequests:{},submissions:{},commitErrors:{}});const release=installDesktopDraftSources(coordinator,storage);return{coordinator,storage,map,reads,dispose(){release();useChatStore.setState(chat);useStagedChangesStore.setState(staged);useSceneUiStore.setState(scene)}}}
test("SAVE50-S01: source capture retains editing/chipped staged batches without confirming, sending or clearing them",async()=>{
 const f=fixture();try{useStagedChangesStore.getState().record("chapter:local","local-novel","章一",{targetKind:"CHAPTER_CONTENT",targetId:"local-chapter",targetLabel:"章一",novelId:"local-novel",op:"modify",request:{url:"/api/novels/local-novel/chapters/local-chapter",method:"PATCH",body:{content:"尚未批准的正文",expectedVersion:3,operationId:crypto.randomUUID()}},items:[{key:"content",field:"content",fieldLabel:"正文",summary:"正文修改"}],updatedAt:1});const before=structuredClone(useStagedChangesStore.getState().batches);const writes:unknown[]=[];f.coordinator.configurePersistence(async value=>{writes.push(value)});await f.coordinator.flushAll();const snapshot=f.coordinator.exportSnapshot();assert.deepEqual((snapshot.sources.staged as {batches:unknown}).batches,before);assert.deepEqual(useStagedChangesStore.getState().batches,before);assert.deepEqual(useStagedChangesStore.getState().chips,[]);assert.equal(useStagedChangesStore.getState().takeForSend("local-novel").length,0);assert.equal(writes.length,1)}finally{f.dispose()}
})
test("SAVE50-S02: chat snapshot uses only its owned account key and existing schema; active and prior unsent drafts retain identities",()=>{
 const f=fixture(),old={...emptyChatSession(),draftId:"previous-draft",draft:"旧草稿"};new ChatSessionRepository("source-test-owner",f.storage).save(old);f.map.set("unowned-cache","private credential must not be read");
 try{const snapshot=f.coordinator.exportSnapshot(),chat=snapshot.sources.chat as {accountId:string;active:{draftId:string;modelChoice:{modelId:null};mode:string;novelCreationRequestId:string};saved:{version:number;drafts:Record<string,{draft:string}>}};assert.equal(chat.accountId,"source-test-owner");assert.equal(chat.active.draftId,"active-draft");assert.equal(chat.active.modelChoice.modelId,null);assert.equal(chat.active.mode,"plan");assert.equal(chat.active.novelCreationRequestId,"stable-create");assert.equal(chat.saved.drafts[old.draftId].draft,old.draft);assert.ok(f.reads.length);assert.ok(f.reads.every(key=>key===chatSessionKey("source-test-owner")));assert.equal(JSON.stringify(snapshot).includes("private credential"),false)}finally{f.dispose()}
})
test("SAVE50-S03: malformed owned chat-session data is retained, blocks durable success and does not hide other available drafts",async()=>{
 const f=fixture(),key=chatSessionKey("source-test-owner");f.map.set(key,'{"version":9,"unknown":"keep original"}');let writes=0;f.coordinator.configurePersistence(async()=>{writes++})
 try{await assert.rejects(f.coordinator.flushAll(),{code:"DRAFT_SOURCE_UNREADABLE"});const snapshot=f.coordinator.exportSnapshot();assert.ok(snapshot.issues.some(issue=>issue.source==="chat"));assert.ok(snapshot.sources.staged);assert.equal(f.map.get(key),'{"version":9,"unknown":"keep original"}');assert.equal(writes,0)}finally{f.dispose()}
})
test("SAVE50-S04: store mutation participates in coordinator revisions and lifecycle installation is reference-counted",()=>{
 const f=fixture(),releaseAgain=installDesktopDraftSources(f.coordinator,f.storage)
 try{const before=f.coordinator.exportSnapshot().revision;useChatStore.setState({draft:"新输入"});assert.ok(f.coordinator.exportSnapshot().revision>before);releaseAgain();assert.ok(f.coordinator.exportSnapshot().sources.chat);assert.deepEqual(Object.keys(f.coordinator.exportSnapshot().sources).sort(),["chat","scene","staged"])}finally{releaseAgain();f.dispose()}
})
test("SAVE50-S05: queued review/improvement actions survive the existing session schema and are captured without execution",()=>{
 const f=fixture(),action={kind:"review" as const,targetType:"CHAPTER_CONTENT" as const,targetId:"queued-chapter"},queued={id:"queued-review",text:"排队审核指定章节",action},old={...emptyChatSession(),draftId:"prior-queued-draft",queuedMessages:[queued]}
 new ChatSessionRepository("source-test-owner",f.storage).save(old);useChatStore.setState({queuedMessages:[queued]})
 try{const chat=f.coordinator.exportSnapshot().sources.chat as {active:{queuedMessages:unknown[]};saved:{drafts:Record<string,{queuedMessages:unknown[]}>}};assert.deepEqual(chat.active.queuedMessages,[queued]);assert.deepEqual(chat.saved.drafts[old.draftId].queuedMessages,[queued]);assert.deepEqual(useChatStore.getState().queuedMessages,[queued]);assert.equal(useChatStore.getState().isGenerating,false)}finally{f.dispose()}
})
test("SAVE50-S06: actual apiSend staging is captured only after the controller drains, without a network PATCH or approval",async()=>{
 const f=fixture(),originalFetch=globalThis.fetch,base={id:"local-chapter",novelId:"local-novel",title:"受控章一",content:"当前稿",version:3},url="/api/novels/local-novel/chapters/local-chapter";let http=0
 globalThis.fetch=async()=>{http++;throw Error("unexpected network")};registerStagedInterception({resolveBatch:()=>({batchKey:"chapter-content:local-chapter",label:"受控章一"}),snapshot:async()=>base})
 const controller=new AutosaveController<string>(async(value,attempt)=>{const result=await apiSend<{chapter:typeof base}>(url,"PATCH",{content:value,expectedVersion:base.version,operationId:attempt.operationId});assert.equal(result.chapter.version,base.version)},60000),release=f.coordinator.register(controller),written:unknown[]=[]
 f.coordinator.configurePersistence(async snapshot=>{written.push(snapshot)})
 try{controller.schedule("仅本地暂存的作者正文");await f.coordinator.flushAll();assert.equal(http,0);assert.equal(written.length,1);const staged=(written[0] as {sources:{staged:{batches:Record<string,StagedBatch>}}}).sources.staged;const batch=staged.batches["chapter-content:local-chapter"],body=batch.changes[0].request.body as {content:string;expectedVersion:number};assert.equal(batch.phase,"editing");assert.equal(body.content,"仅本地暂存的作者正文");assert.equal(body.expectedVersion,3);assert.equal(base.content,"当前稿");assert.deepEqual(useStagedChangesStore.getState().chips,[]);assert.equal(useStagedChangesStore.getState().takeForSend("local-novel").length,0)}finally{release();controller.dispose();registerStagedInterception(null);globalThis.fetch=originalFetch;f.dispose()}
})
