import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,readFile,writeFile,rm,symlink,stat} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomUUID} from 'node:crypto'
import {DraftJournal} from '../../desktop/main/draft-journal'
import type {DraftSnapshot} from '../../desktop/shared/drafts'
import {CommitDurabilityError} from '../../desktop/core/versioned-store'
const snapshot=(revision=1,text='未批准的本地草稿'):DraftSnapshot=>({version:1,revision,createdAt:new Date().toISOString(),autosaves:[{id:randomUUID(),draft:{revision,pending:{revision,value:text,operationId:randomUUID()}}}],sources:{staged:{batches:{},chips:[]}},issues:[]})
async function fixture(options:ConstructorParameters<typeof DraftJournal>[1]={}){const root=await mkdtemp(join(tmpdir(),'xuanxiang-journal-')),journal=new DraftJournal(root,options),release=journal.activate('window-1');return{root,journal,release,async close(){release();await rm(root,{recursive:true,force:true})}}}
test('durable drafts survive a fresh journal and contain only the bounded data snapshot',async()=>{const f=await fixture();try{const input=snapshot(),receipt=await f.journal.persist('window-1',input);assert.equal(receipt.digest.length,64);assert.equal(receipt.clientRevision,1);assert.deepEqual(await new DraftJournal(f.root).read(),input);assert.equal((await stat(join(f.root,'drafts.json'))).mode&0o777,0o600)}finally{await f.close()}})
test('old revisions and same-revision different data cannot overwrite acknowledged drafts',async()=>{const f=await fixture();try{const first=snapshot(2),ack=await f.journal.persist('window-1',first);assert.deepEqual(await f.journal.persist('window-1',{...first,createdAt:new Date(Date.now()+1000).toISOString()}),ack);await assert.rejects(f.journal.persist('window-1',snapshot(1)),/修订/);await assert.rejects(f.journal.persist('window-1',snapshot(2,'不同草稿')),/修订/);assert.deepEqual(await f.journal.read(),first)}finally{await f.close()}})
test('invalid version, unknown source, non-data values and oversized drafts leave the valid snapshot unchanged',async()=>{const f=await fixture();try{const good=snapshot();await f.journal.persist('window-1',good);for(const bad of [{...snapshot(2),version:2},{...snapshot(2),sources:{arbitraryBrowserCache:{}}},{...snapshot(2),sources:{chat:{key:()=>1}}},{...snapshot(2),sources:{chat:{draft:'x'.repeat(16*1024*1024)}}}])await assert.rejects(f.journal.persist('window-1',bad as DraftSnapshot));assert.deepEqual(await f.journal.read(),good)}finally{await f.close()}})
test('revoking the renderer while a write waits at rename preserves the previous durable draft',async()=>{let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});let delay=false;const f=await fixture({beforeRename:()=>delay?gate:Promise.resolve()});try{const first=snapshot();await f.journal.persist('window-1',first);delay=true;const pending=f.journal.persist('window-1',snapshot(2)),rejected=assert.rejects(pending,/窗口/);await new Promise(resolve=>setTimeout(resolve,10));f.release();release();await rejected;assert.deepEqual(await f.journal.read(),first)}finally{release();await f.close()}})
test('a new renderer owner can start its own sequence but a stale owner can never write again',async()=>{const f=await fixture();try{await f.journal.persist('window-1',snapshot(5));f.release();const end=f.journal.activate('window-2');const next=snapshot(0,'重开窗口的草稿');const ack=await f.journal.persist('window-2',next);assert.equal(ack.revision,2);await assert.rejects(f.journal.persist('window-1',snapshot(6)),/窗口/);assert.deepEqual(await f.journal.read(),next);end()}finally{await f.close()}})
test('corrupt journal data and checksum mismatches are preserved and block overwrite',async()=>{const f=await fixture();try{await f.journal.persist('window-1',snapshot());const path=join(f.root,'drafts.json'),record=JSON.parse(await readFile(path,'utf8'));record.snapshot.sources={staged:{tampered:true}};await writeFile(path,JSON.stringify(record));await assert.rejects(f.journal.read(),/校验|格式/);await assert.rejects(f.journal.persist('window-1',snapshot(2)),/校验|格式/);assert.deepEqual(JSON.parse(await readFile(path,'utf8')),record)}finally{await f.close()}})
test('the journal never follows a substituted file symlink outside its owned root',async()=>{const f=await fixture(),outside=await mkdtemp(join(tmpdir(),'xuanxiang-outside-'));try{const path=join(outside,'private.txt');await writeFile(path,'保留外部文件');await symlink(path,join(f.root,'drafts.json'));await assert.rejects(f.journal.read(),/文件|目录/);await assert.rejects(f.journal.persist('window-1',snapshot()),/文件|目录/);assert.equal(await readFile(path,'utf8'),'保留外部文件')}finally{await f.close();await rm(outside,{recursive:true,force:true})}})
test('a directory-sync failure is not acknowledged; retry validates the committed bytes and syncs again',async()=>{let fail=true;const f=await fixture({beforeDirectorySync:async()=>{if(fail)throw Error('isolated sync failure')}});try{const input=snapshot();await assert.rejects(f.journal.persist('window-1',input),CommitDurabilityError);assert.deepEqual(await f.journal.read(),input);fail=false;const receipt=await f.journal.persist('window-1',input);assert.equal(receipt.digest.length,64);assert.equal(receipt.revision,1)}finally{await f.close()}})
test('optional object properties preserve ordinary JSON semantics without losing defined draft data',async()=>{const f=await fixture();try{const input={...snapshot(),sources:{staged:{title:'草稿',unused:undefined}}};await f.journal.persist('window-1',input);assert.deepEqual((await f.journal.read())?.sources,{staged:{title:'草稿'}})}finally{await f.close()}})
test('an external replacement at the commit boundary is not silently overwritten',async()=>{let replace=false;const f=await fixture({beforeRename:async()=>{if(replace)await writeFile(join(f.root,'drafts.json'),'外部待恢复数据')}});try{await f.journal.persist('window-1',snapshot());replace=true;await assert.rejects(f.journal.persist('window-1',snapshot(2)),/校验|格式|变化/);assert.equal(await readFile(join(f.root,'drafts.json'),'utf8'),'外部待恢复数据')}finally{await f.close()}})
test('close confirmation accepts only the current durable receipt for the active window lifetime',async()=>{const f=await fixture();try{const first=await f.journal.persist('window-1',snapshot());await f.journal.confirm('window-1',first);await assert.rejects(f.journal.confirm('window-1',{...first,digest:'0'.repeat(64)}),/确认/);const next=await f.journal.persist('window-1',snapshot(2));await assert.rejects(f.journal.confirm('window-1',first),/确认/);await f.journal.confirm('window-1',next);f.release();f.journal.activate('window-1');await assert.rejects(f.journal.confirm('window-1',next),/确认/)}finally{await f.close()}})
test('a renamed but unacknowledged snapshot cannot confirm close even if its digest is known',async()=>{const f=await fixture({beforeDirectorySync:async()=>{throw Error('isolated directory sync failure')}});try{await assert.rejects(f.journal.persist('window-1',snapshot()),CommitDurabilityError);const disk=JSON.parse(await readFile(join(f.root,'drafts.json'),'utf8'));await assert.rejects(f.journal.confirm('window-1',{revision:disk.revision,digest:disk.digest,clientRevision:disk.snapshot.revision}),/确认/)}finally{await f.close()}})
test('a snapshot with unreadable sources cannot replace a complete durable recovery record',async()=>{const f=await fixture();try{const before=snapshot();await f.journal.persist('window-1',before);await assert.rejects(f.journal.persist('window-1',{...snapshot(2),issues:[{source:'staged',code:'DRAFT_SOURCE_UNREADABLE'}]}),/读取/);assert.deepEqual(await f.journal.read(),before)}finally{await f.close()}})
