import assert from 'node:assert/strict'
import {test} from 'node:test'
import {randomUUID} from 'node:crypto'
import {mkdtemp,mkdir,writeFile,readFile,readdir,realpath,rm,symlink,link} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {collectClosedRootFiles} from '../../desktop/main/owned-root-files'
import {directoryIdentity} from '../../desktop/core/root-ownership'

async function fixture(){const base=await realpath(await mkdtemp(join(tmpdir(),'xuanxiang-inventory65-'))),root=join(base,'root');await mkdir(root);const put=async(path:string,bytes='owned')=>{await mkdir(join(root,path,'..'),{recursive:true});await writeFile(join(root,path),bytes)};await put('xuanxiang-app.json',JSON.stringify({schemaVersion:1,app:'Xuanxiangxiezuo-Desktop',id:randomUUID(),phase:'ready',inboxReady:true}));await put('catalog.json',JSON.stringify({schemaVersion:1,revision:0,value:[]}));return{base,root,put,identity:await directoryIdentity(root),close:()=>rm(base,{recursive:true,force:true})}}

test('INV65-01: actual upgrade snapshot pair and explicit empty PG directories are owned, while lookalike snapshots/unknown descendants are preserved',async()=>{
 const f=await fixture();try{const snapshot=`inbox/snapshots/before-upgrade-${Date.now()}-${randomUUID()}.tar.gz`,recognized=[snapshot,snapshot+'.json','session/Code Cache/electron-preload/'+('A'.repeat(64))+'-'+('B'.repeat(64))+'.cache'],unknown=['inbox/snapshots/author.tar.gz',snapshot+'.tmp',`inbox/snapshots/before-upgrade-12-${randomUUID()}.tar.gz`,'inbox/database/user-empty/PG_VERSION','session/author/cache.db'];for(const file of [...recognized,...unknown])await f.put(file);for(const dir of ['inbox/database/pg_notify','inbox/database/pg_wal/archive_status','session/blob_storage'])await mkdir(join(f.root,dir),{recursive:true});const inventory=await collectClosedRootFiles(f.identity,()=>{});for(const file of recognized)assert.ok(inventory.files.includes(file),file);for(const file of unknown){assert.equal(inventory.files.includes(file),false,file);assert.equal(await readFile(join(f.root,file),'utf8'),'owned')}for(const dir of ['inbox/database/pg_notify','inbox/database/pg_wal/archive_status'])assert.ok(inventory.directories.includes(dir));assert.ok(inventory.preserved.includes('inbox/database/user-empty'));assert.ok(inventory.preserved.includes('session/author'));assert.ok(!inventory.directories.includes('inbox/database/user-empty'))}finally{await f.close()}
})

test('INV65-02: a recognized empty PG directory symlink is never followed or owned; unrelated directory links remain untouched',async()=>{
 for(const recognized of [true,false]){const f=await fixture();try{const outside=join(f.base,'author-directory');await mkdir(outside);await writeFile(join(outside,'draft.txt'),'external draft');await mkdir(join(f.root,'inbox/database'),{recursive:true});const name=recognized?'pg_notify':'author-directory';await symlink(outside,join(f.root,'inbox/database',name));if(recognized)await assert.rejects(collectClosedRootFiles(f.identity,()=>{}));else{const inventory=await collectClosedRootFiles(f.identity,()=>{});assert.equal(inventory.directories.some(path=>path.includes(name)),false);assert.ok(inventory.preserved.includes('inbox/database/'+name))}assert.equal(await readFile(join(outside,'draft.txt'),'utf8'),'external draft')}finally{await f.close()}}
})

test('INV65-03: exact snapshot names cannot claim a hardlinked external backup, and catalogued work subtrees override every recognized file/directory name',async()=>{
 const f=await fixture();try{const snapshot=`inbox/snapshots/before-upgrade-${Date.now()}-${randomUUID()}.tar.gz`;await mkdir(join(f.root,'inbox/snapshots'),{recursive:true});await writeFile(join(f.base,'external-backup'),'external author backup');await link(join(f.base,'external-backup'),join(f.root,snapshot));await assert.rejects(collectClosedRootFiles(f.identity,()=>{}));assert.equal(await readFile(join(f.base,'external-backup'),'utf8'),'external author backup');await rm(join(f.root,snapshot));await f.put('session/Local Storage/leveldb/000004.ldb','work bytes');await mkdir(join(f.root,'session/Local Storage/leveldb/index-dir'));await f.put('catalog.json',JSON.stringify({schemaVersion:1,revision:2,value:[{path:join(f.root,'session/Local Storage')}]}));const inventory=await collectClosedRootFiles(f.identity,()=>{});assert.equal(inventory.files.some(path=>path.startsWith('session/Local Storage/')),false);assert.equal(inventory.directories.includes('session/Local Storage'),false);assert.ok(inventory.preserved.includes('session/Local Storage'));assert.equal(await readFile(join(f.root,'session/Local Storage/leveldb/000004.ldb'),'utf8'),'work bytes');assert.deepEqual(await readdir(join(f.root,'session/Local Storage/leveldb/index-dir')),[])}finally{await f.close()}
})
