import assert from 'node:assert/strict'
import {test} from 'node:test'
import {recoveryPreview} from '../../src/lib/desktop/recovery-preview'
const row=(source:string,value:unknown,path='source')=>({id:'test',source,path,reason:'RESTORE_DISABLED' as const,createdAt:'2026-10-08T00:00:00.000Z',value})
test('recovered autosave shows user content and both different unsaved attempts without operation metadata',()=>{
 const value={revision:3,status:'error',paused:true,pending:{revision:3,operationId:'private-request-id',value:{content:'新的正文'}},failed:{revision:2,operationId:'previous-id',value:{content:'上次未保存的正文'}},latest:{revision:3,operationId:'private-request-id',value:{content:'新的正文'}}},before=structuredClone(value),result=recoveryPreview(row('autosaves',value))
 assert.match(result.text,/新的正文/);assert.match(result.text,/上次未保存的正文/);assert.doesNotMatch(result.text,/operationId|private-request-id|paused|status|pending/);assert.deepEqual(value,before);assert.equal(result.meaningful,true)
})
test('idle autosaves are empty presentation records, while unknown data stays exportable without raw internal JSON',()=>{assert.equal(recoveryPreview(row('autosaves',{revision:0,status:'idle',pending:null,failed:null,inFlight:null,latest:null})).empty,true);const result=recoveryPreview(row('unknown',{secretInternal:'value',endpoint:'/api/path'}));assert.equal(result.empty,false);assert.equal(result.meaningful,false);assert.doesNotMatch(result.text,/secretInternal|endpoint|api\/path/);assert.match(result.text,/导出/)})
test('staged changes present original manuscript/outline and labels, never request paths or executable payload',()=>{const result=recoveryPreview(row('staged',{batches:{id:{label:'第一章',changes:[{targetKind:'CHAPTER_CONTENT',request:{url:'/api/novels/private/chapters/row',method:'PATCH',body:{content:'正文原文',expectedVersion:2}}},{targetKind:'CHAPTER_OUTLINE',request:{body:{outline:'大纲原文'}}}]}}}));assert.match(result.text,/第一章/);assert.match(result.text,/正文原文/);assert.match(result.text,/大纲原文/);assert.doesNotMatch(result.text,/expectedVersion|PATCH|private|targetKind/);assert.equal(result.meaningful,true)})
test('chat preview reads user draft and queued messages from both durable snapshot and owned browser cache',()=>{for(const value of [{active:{draft:'对话输入',queuedMessages:[{text:'队列输入'}]},saved:{drafts:{one:{draft:'另一份输入',pendingRequest:{body:'private-execution'}}}}},JSON.stringify({version:1,drafts:{one:{draft:'对话输入',queuedMessages:[{text:'队列输入'}]},two:{draft:'另一份输入'}}})]){const result=recoveryPreview(row('chat',value,typeof value==='string'?'owned-cache':'source'));assert.match(result.text,/对话输入/);assert.match(result.text,/队列输入/);assert.match(result.text,/另一份输入/);assert.doesNotMatch(result.text,/private-execution|queuedMessages|drafts/);assert.equal(result.meaningful,true)}})
test('scene and comment previews preserve author prose and do not display serialized bookkeeping',()=>{const scene=recoveryPreview(row('scene',{drafts:{id:{value:{name:'雨夜码头',description:'潮水拍打岸边',version:1,novelId:'private-id'}}},imageDrafts:{id:{prompt:'暖色灯光'}}}));assert.match(scene.text,/雨夜码头/);assert.match(scene.text,/潮水拍打岸边/);assert.match(scene.text,/暖色灯光/);assert.doesNotMatch(scene.text,/private-id|novelId/);const comments=recoveryPreview(row('comments',{rows:[{content:'这里需要补伏笔',anchor:{quote:'他回头'}}]}));assert.match(comments.text,/这里需要补伏笔/);assert.match(comments.text,/他回头/)})
test('oversized previews are explicitly truncated without altering full retained data',()=>{const value='文'.repeat(200000),item=row('chat',{draft:value}),result=recoveryPreview(item);assert.equal(result.truncated,true);assert.ok(result.text.length<=100100);assert.equal((item.value as {draft:string}).draft.length,200000)})
test('legacy plain drafts remain readable and idle-shaped unknown records are never silently hidden',()=>{
 assert.equal(recoveryPreview(row('chat','旧版纯文字')).text,'旧版纯文字')
 assert.equal(recoveryPreview(row('autosaves',{draft:'旧版编辑副本',operationId:'inert-metadata'})).text,'旧版编辑副本')
 for(const value of [{status:'idle',content:'尚有正文'},{status:'idle',revision:0,pending:null,failed:null,inFlight:null,latest:null,unknown:'仍需核对'}])assert.equal(recoveryPreview(row('autosaves',value)).empty,false)
})
test('original theme, item and structured setting prose is projected through known fields only',()=>{
 const value={synopsis:'故事简介',sellingPoints:'卖点',referenceCases:'参考案例',targetAudience:'读者',appearance:'旧铜外观',acquisition:'由师父传承',effects:[{name:'听潮',description:'能听到远方海浪'}],content:{rules:'进阶有代价',levels:[{name:'潮汐级',condition:'经历风暴',abilities:[{name:'水声',description:'读懂潮汐'}],children:[{name:'初阶',description:'先学会倾听'}]}],concepts:[{term:'回响',explanation:'海中的记忆'}],request:{content:'不可读取的请求'}}},preview=recoveryPreview(row('autosaves',{pending:{value}}))
 for(const text of ['故事简介','卖点','参考案例','读者','旧铜外观','由师父传承','能听到远方海浪','进阶有代价','经历风暴','读懂潮汐','先学会倾听','海中的记忆'])assert.ok(preview.text.includes(text),text)
 assert.doesNotMatch(preview.text,/不可读取的请求/)
})
